// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
#include "relay/control/generated_protocol.hpp"

#include <algorithm>
#include <array>

namespace relay {
namespace {

constexpr std::array<ProtocolFieldSpec, 0> no_fields{};

constexpr std::array<ProtocolFieldSpec, 1> fields_runtime_step{{
    {"frames", ProtocolValueType::integer, false, false, true, true, 1, 10000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_render_capture{{
    {"path", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^(captures/)?[A-Za-z0-9][A-Za-z0-9._-]*\\.(bmp|png)$", ""},
    {"source", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "vulkan|deterministic"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_render_capture_async{{
    {"path", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^(captures/)?[A-Za-z0-9][A-Za-z0-9._-]*\\.(bmp|png)$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_render_capture_status{{
    {"job", ProtocolValueType::integer, true, false, true, false, 1, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_assets_import_model{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 5U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.(gltf|glb|fbx|obj|dae|blend)$", ""},
    {"instantiate", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"preset", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "scene|static_mesh"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_logs_read{{
    {"after", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_performance_read{{
    {"after_frame", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
    {"limit", ProtocolValueType::integer, false, false, true, true, 1, 240, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_video_start{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.webm$", ""},
    {"fps", ProtocolValueType::integer, false, false, true, true, 1, 60, 0U, 0U, "", ""},
    {"maximum_frames", ProtocolValueType::integer, false, false, true, true, 1, 3600, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_inspect{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scene_create{{
    {"name", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 128U, "", ""},
    {"parent", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_destroy{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 10> fields_scene_set_transform{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"px", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"py", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"pz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"rx", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"ry", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"rz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sx", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sy", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_scene_set_camera{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"active", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"field_of_view_y_degrees", ProtocolValueType::number, false, false, true, true, 1.01, 178.99, 0U, 0U, "", ""},
    {"near_plane", ProtocolValueType::number, false, false, true, true, 0.0001, 1000, 0U, 0U, "", ""},
    {"far_plane", ProtocolValueType::number, false, false, true, true, 0.001, 1000000, 0U, 0U, "", ""},
    {"orthographic_height", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_scene_set_renderer{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"mesh", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9._:-]+$", ""},
    {"material", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9._:-]+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scene_set_parent{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"parent", ProtocolValueType::string, true, true, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 6> fields_scene_set_animation{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"clip", ProtocolValueType::integer, false, false, true, true, 0, 255, 0U, 0U, "", ""},
    {"playing", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"loop", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"speed", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"time_seconds", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_scene_set_morph{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"target", ProtocolValueType::integer, false, false, true, true, 0, 63, 0U, 0U, "", ""},
    {"weight", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"reset", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 13> fields_scene_set_light{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "directional|point|spot"},
    {"red", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"green", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"blue", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"intensity", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"constant", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"linear", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"quadratic", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"inner_cone", ProtocolValueType::number, false, false, true, true, 0, 1.5707963267948966, 0U, 0U, "", ""},
    {"outer_cone", ProtocolValueType::number, false, false, true, true, 0.0001, 1.5707963267948966, 0U, 0U, "", ""},
    {"range", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_save{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 12U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay\\.json$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_load{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 12U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay\\.json$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_trace_start{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay-trace\\.jsonl$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_trace_replay{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay-trace\\.jsonl$", ""},
}};

constexpr std::array<ProtocolMethodSpec, 41> methods{{
    {"runtime.status", "runtime_status", "Inspect Relay runtime", "Read the current run, pause, frame, simulation time and resolution state.", true, false, false, no_fields},
    {"runtime.pause", "runtime_pause", "Pause Relay runtime", "Pause automatic simulation so the scene can be inspected deterministically.", false, false, true, no_fields},
    {"runtime.resume", "runtime_resume", "Resume Relay runtime", "Resume automatic simulation after an inspection or controlled frame step.", false, false, true, no_fields},
    {"runtime.step", "runtime_step", "Step Relay frames", "Advance an exact number of deterministic simulation frames, including while paused.", false, false, false, fields_runtime_step},
    {"runtime.quit", "runtime_shutdown", "Shut down Relay runtime", "Request an orderly shutdown of the runtime owned by this MCP bridge.", false, false, true, no_fields},
    {"render.capture", "render_capture", "Capture Relay frame", "Save the current rendered frame in Relay's captures directory for visual inspection.", false, false, false, fields_render_capture},
    {"render.capture_async", "render_capture_async", "Queue Relay frame capture", "Copy the deterministic frame and encode it on Relay's bounded background worker.", false, false, false, fields_render_capture_async},
    {"render.capture_status", "render_capture_status", "Inspect capture job", "Check whether an asynchronous capture is queued, writing, complete or failed.", true, false, false, fields_render_capture_status},
    {"render.capabilities", "render_capabilities", "Inspect graphics capabilities", "Create a temporary Vulkan device and report adapter and modern rendering support.", true, false, false, no_fields},
    {"render.graph", "render_graph", "Inspect render graph", "Read compiled render passes, resources, dependencies and access transitions.", true, false, false, no_fields},
    {"render.shader_interfaces", "render_shader_interfaces", "Inspect shader interfaces", "Read SPIR-V-reflected stages, locations, descriptor bindings and push-constant sizes from the live Vulkan pipeline.", true, false, false, no_fields},
    {"render.assets", "render_assets", "Inspect render assets", "List built-in and imported meshes, materials and textures currently available to scene renderer components.", true, false, false, no_fields},
    {"assets.formats", "asset_import_formats", "Inspect model import formats", "Report model formats and feature coverage available in this Relay build, including Godot-compatible interchange paths.", true, false, false, no_fields},
    {"assets.import_model", "asset_import_model", "Import project model", "Import a model from the project-local assets directory using a content-addressed identity and optionally instantiate its node hierarchy.", false, false, false, fields_assets_import_model},
    {"logs.read", "logs_read", "Read Relay logs", "Read structured engine log entries newer than a sequence number.", true, false, false, fields_logs_read},
    {"performance.read", "performance_read", "Read Relay performance", "Read bounded per-frame CPU/GPU timing, draw/resource counts, entities and process memory.", true, false, false, fields_performance_read},
    {"input.recent", "input_recent", "Read recent Relay input", "Read the bounded normalized keyboard, mouse and gamepad input event history.", true, false, false, no_fields},
    {"video.start", "video_start", "Start Relay video", "Begin sampling deterministic frames into a bounded asynchronous WebM recording.", false, false, false, fields_video_start},
    {"video.capabilities", "video_capabilities", "Inspect video capabilities", "Report whether this Relay build found the FFmpeg WebM encoder.", true, false, false, no_fields},
    {"video.stop", "video_stop", "Stop Relay video", "Finish queued frames and encode the active recording to WebM with FFmpeg.", false, false, false, no_fields},
    {"video.status", "video_status", "Inspect Relay video", "Read recording state, submitted frames and explicitly reported frame drops.", true, false, false, no_fields},
    {"scene.list", "scene_list", "List scene entities", "List every live entity with its name, parent and local transform.", true, false, false, no_fields},
    {"scene.inspect", "scene_inspect", "Inspect scene entity", "Inspect one entity using its stable generation-checked handle.", true, false, false, fields_scene_inspect},
    {"scene.create", "scene_create", "Create scene entity", "Create a named entity, optionally parented to another live entity.", false, false, false, fields_scene_create},
    {"scene.destroy", "scene_destroy", "Destroy scene entity", "Destroy an entity and its descendants as one undoable transaction.", false, true, false, fields_scene_destroy},
    {"scene.set_transform", "scene_set_transform", "Set entity transform", "Update selected local position, Euler rotation or scale fields in one transaction.", false, false, false, fields_scene_set_transform},
    {"scene.set_camera", "scene_set_camera", "Configure entity camera", "Add, update or remove a perspective or orthographic camera; activating one deactivates the previous camera.", false, false, false, fields_scene_set_camera},
    {"scene.set_renderer", "scene_set_renderer", "Configure entity renderer", "Attach a registered built-in or imported mesh and material to an entity, or remove its renderer component.", false, false, false, fields_scene_set_renderer},
    {"scene.set_parent", "scene_set_parent", "Set entity parent", "Reparent an entity safely; use null to move it to the scene root.", false, false, false, fields_scene_set_parent},
    {"scene.undo", "scene_undo", "Undo scene change", "Undo the most recent scene transaction and restore exact entity generations.", false, false, false, no_fields},
    {"scene.redo", "scene_redo", "Redo scene change", "Reapply the most recently undone scene transaction.", false, false, false, no_fields},
    {"scene.set_animation", "scene_set_animation", "Control imported animation", "Configure clip, playback, looping, speed and seek time on an imported model root.", false, false, false, fields_scene_set_animation},
    {"scene.set_morph", "scene_set_morph", "Set imported morph weight", "Override a mesh morph weight, or reset all overrides to imported defaults and animation.", false, false, false, fields_scene_set_morph},
    {"scene.set_light", "scene_set_light", "Configure scene light", "Add, update or remove a directional, point or spot light.", false, false, false, fields_scene_set_light},
    {"scene.snapshot", "scene_snapshot", "Snapshot Relay scene", "Return deterministic scene JSON plus reflected component field metadata.", true, false, false, no_fields},
    {"scene.save", "scene_save", "Save Relay scene", "Atomically save the current scene in Relay's project-local scenes directory.", false, true, true, fields_scene_save},
    {"scene.load", "scene_load", "Load Relay scene", "Validate, migrate and load a project scene as one undoable transaction.", false, false, false, fields_scene_load},
    {"trace.start", "trace_start", "Start Relay trace", "Record frame-stamped agent commands and normalized human input events.", false, false, false, fields_trace_start},
    {"trace.stop", "trace_stop", "Stop Relay trace", "Atomically persist the active deterministic trace in Relay's traces directory.", false, false, false, no_fields},
    {"trace.status", "trace_status", "Inspect Relay trace", "Read trace recording state, path and current event count.", true, false, false, no_fields},
    {"trace.replay", "trace_replay", "Replay Relay trace", "Validate and replay a trace against the fixed-step runtime at its recorded frame offsets.", false, false, false, fields_trace_replay},
}};

} // namespace

std::span<const ProtocolMethodSpec> protocol_methods() { return methods; }

const ProtocolMethodSpec* find_protocol_method(const std::string_view method) {
    const auto found = std::find_if(methods.begin(), methods.end(), [method](const auto& candidate) {
        return candidate.method == method;
    });
    return found == methods.end() ? nullptr : &*found;
}

} // namespace relay
