// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
#include "relay/control/generated_protocol.hpp"

#include <algorithm>
#include <array>

namespace relay {
namespace {

constexpr std::array<ProtocolFieldSpec, 0> no_fields{};

constexpr std::array<ProtocolFieldSpec, 1> fields_runtime_step{{
    {"frames", ProtocolValueType::integer, false, false, true, true, 1, 10000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_editor_camera_set{{
    {"target_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"target_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"target_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"yaw", ProtocolValueType::number, false, false, true, true, -1000, 1000, 0U, 0U, "", ""},
    {"pitch", ProtocolValueType::number, false, false, true, true, -1.55, 1.55, 0U, 0U, "", ""},
    {"distance", ProtocolValueType::number, false, false, true, true, 0.25, 5000, 0U, 0U, "", ""},
    {"mode", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "inspector|scene"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_editor_camera_frame{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_render_capture{{
    {"path", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^(captures/)?[A-Za-z0-9][A-Za-z0-9._-]*\\.(bmp|png)$", ""},
    {"source", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "vulkan|deterministic"},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_render_capture_async{{
    {"path", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^(captures/)?[A-Za-z0-9][A-Za-z0-9._-]*\\.(bmp|png)$", ""},
    {"source", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "vulkan|deterministic"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_render_capture_cancel{{
    {"job", ProtocolValueType::integer, true, false, true, false, 1, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_render_capture_status{{
    {"job", ProtocolValueType::integer, true, false, true, false, 1, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_assets_import_model{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 5U, 128U, "^[A-Za-z0-9][A-Za-z0-9._ /-]*\\.(gltf|glb|fbx|obj|dae|blend)$", ""},
    {"instantiate", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"preset", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "scene|static_mesh"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_assets_browse{{
    {"directory", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^([A-Za-z0-9][A-Za-z0-9._ /-]*)?$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_assets_search{{
    {"query", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 64U, "", ""},
    {"kinds", ProtocolValueType::string_array, false, false, false, false, 0, 0, 0U, 12U, "^(folder|model|scene|template|image|shader|script|text|media|audio|other)$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_assets_create_folder{{
    {"path", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9][A-Za-z0-9._ /-]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_assets_move{{
    {"from", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9][A-Za-z0-9._ /-]*$", ""},
    {"to", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9][A-Za-z0-9._ /-]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_assets_delete{{
    {"path", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9][A-Za-z0-9._ /-]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_logs_read{{
    {"after", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_performance_read{{
    {"after_frame", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
    {"limit", ProtocolValueType::integer, false, false, true, true, 1, 240, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_profiler_read{{
    {"frames", ProtocolValueType::integer, false, false, true, true, 1, 1200, 0U, 0U, "", ""},
    {"frame", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
    {"game_only", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"history", ProtocolValueType::integer, false, false, true, true, 0, 1200, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_profiler_set{{
    {"paused", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"clear", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_graphics_set_settings{{
    {"global_illumination", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"reflections", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"frame_rate_limit", ProtocolValueType::integer, false, false, true, true, 0, 1000, 0U, 0U, "", ""},
    {"vsync", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_input_set_map{{
    {"map", ProtocolValueType::string, true, false, false, false, 0, 0, 2U, 262144U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_input_simulate{{
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 64U, "^[A-Za-z_][A-Za-z0-9_]*$", ""},
    {"value", ProtocolValueType::number, false, false, true, true, -1, 1, 0U, 0U, "", ""},
    {"frames", ProtocolValueType::integer, false, false, true, true, 1, 3600, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_video_start{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.webm$", ""},
    {"fps", ProtocolValueType::integer, false, false, true, true, 1, 60, 0U, 0U, "", ""},
    {"maximum_frames", ProtocolValueType::integer, false, false, true, true, 1, 3600, 0U, 0U, "", ""},
    {"source", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "vulkan|deterministic"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_inspect{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_scene_create{{
    {"name", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 128U, "", ""},
    {"parent", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "Node|Camera|DirectionalLight|PointLight|SpotLight|RigidBody|StaticBody|StaticMesh|AudioSource|ReverbZone|MusicPlayer"},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_destroy{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_duplicate{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 11> fields_scene_set_transform{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"px", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"py", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"pz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"rx", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"ry", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"rz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sx", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sy", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"sz", ProtocolValueType::number, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 1000000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 9> fields_scene_set_camera{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"active", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"field_of_view_y_degrees", ProtocolValueType::number, false, false, true, true, 1.01, 178.99, 0U, 0U, "", ""},
    {"near_plane", ProtocolValueType::number, false, false, true, true, 0.0001, 1000, 0U, 0U, "", ""},
    {"far_plane", ProtocolValueType::number, false, false, true, true, 0.001, 1000000, 0U, 0U, "", ""},
    {"orthographic_height", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"exposure_ev", ProtocolValueType::number, false, false, true, true, -16, 16, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_scene_set_renderer{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"mesh", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9._:-]+$", ""},
    {"material", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9._:-]+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scene_set_parent{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"parent", ProtocolValueType::string, true, true, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_scene_set_animation{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"clip", ProtocolValueType::integer, false, false, true, true, 0, 255, 0U, 0U, "", ""},
    {"playing", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"loop", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"speed", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"time_seconds", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 5> fields_scene_set_morph{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"target", ProtocolValueType::integer, false, false, true, true, 0, 63, 0U, 0U, "", ""},
    {"weight", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"reset", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 16> fields_scene_set_collider{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "box|sphere|capsule|convex|mesh"},
    {"center_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"center_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"center_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"half_x", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"half_y", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"half_z", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"radius", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"half_height", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"mesh", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9._:-]*$", ""},
    {"layer", ProtocolValueType::integer, false, false, true, true, 1, 4294967295, 0U, 0U, "", ""},
    {"mask", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 8> fields_physics_raycast{{
    {"origin_x", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"origin_y", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"origin_z", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_x", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_y", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_z", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"maximum_distance", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"layer_mask", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_physics_overlaps{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_physics_body_status{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_physics_contact_events{{
    {"after", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_physics_apply_impulse{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"impulse_x", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"impulse_y", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"impulse_z", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"point_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"point_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"point_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 11> fields_scene_set_physics_body{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "static|dynamic"},
    {"mass", ProtocolValueType::number, false, false, true, true, 1e-06, 1000000, 0U, 0U, "", ""},
    {"gravity_scale", ProtocolValueType::number, false, false, true, true, 0, 100, 0U, 0U, "", ""},
    {"restitution", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"friction", ProtocolValueType::number, false, false, true, true, 0, 10, 0U, 0U, "", ""},
    {"linear_damping", ProtocolValueType::number, false, false, true, true, 0, 100, 0U, 0U, "", ""},
    {"angular_damping", ProtocolValueType::number, false, false, true, true, 0, 100, 0U, 0U, "", ""},
    {"lock_rotation", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scripts_trust{{
    {"trusted", ProtocolValueType::boolean, true, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scripts_read{{
    {"path", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9_][A-Za-z0-9._/-]*\\.(cpp|cc|cxx|hpp|h|hh)$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scripts_write{{
    {"path", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9_][A-Za-z0-9._/-]*\\.(cpp|cc|cxx|hpp|h|hh)$", ""},
    {"source", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 262144U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scripts_create{{
    {"behaviour", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z_][A-Za-z0-9_]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 24> fields_scene_set_joint{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "fixed|point|hinge|slider|distance"},
    {"connected", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^(\\d+:\\d+)?$", ""},
    {"anchor_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"anchor_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"anchor_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"axis_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"axis_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"axis_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"connected_anchor_x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"connected_anchor_y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"connected_anchor_z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"limits", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"limit_min", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"limit_max", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"motor", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"motor_speed", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"motor_force", ProtocolValueType::number, false, false, true, true, 0, 1000000000, 0U, 0U, "", ""},
    {"spring_frequency", ProtocolValueType::number, false, false, true, true, 0, 1000, 0U, 0U, "", ""},
    {"spring_damping", ProtocolValueType::number, false, false, true, true, 0, 100, 0U, 0U, "", ""},
    {"collide_connected", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 17> fields_scene_set_audio_source{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"clip", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^([A-Za-z0-9_-][A-Za-z0-9._ /-]*\\.(wav|WAV|flac|FLAC|mp3|MP3|ogg|OGG))?$", ""},
    {"bus", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"volume_db", ProtocolValueType::number, false, false, true, true, -80, 24, 0U, 0U, "", ""},
    {"pitch", ProtocolValueType::number, false, false, true, true, 0.1, 4, 0U, 0U, "", ""},
    {"pan", ProtocolValueType::number, false, false, true, true, -1, 1, 0U, 0U, "", ""},
    {"loop", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"play_on_start", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"spatial", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"min_distance", ProtocolValueType::number, false, false, true, true, 0.01, 1000000, 0U, 0U, "", ""},
    {"max_distance", ProtocolValueType::number, false, false, true, true, 0.01, 1000000, 0U, 0U, "", ""},
    {"rolloff", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "inverse|inverse_square|linear"},
    {"doppler", ProtocolValueType::number, false, false, true, true, 0, 5, 0U, 0U, "", ""},
    {"occlusion", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"reverb_send", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 14> fields_scene_set_reverb_zone{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"shape", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "sphere|box"},
    {"radius", ProtocolValueType::number, false, false, true, true, 0.01, 100000, 0U, 0U, "", ""},
    {"half_x", ProtocolValueType::number, false, false, true, true, 0.01, 100000, 0U, 0U, "", ""},
    {"half_y", ProtocolValueType::number, false, false, true, true, 0.01, 100000, 0U, 0U, "", ""},
    {"half_z", ProtocolValueType::number, false, false, true, true, 0.01, 100000, 0U, 0U, "", ""},
    {"fade", ProtocolValueType::number, false, false, true, true, 0, 10000, 0U, 0U, "", ""},
    {"preset", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "room|small_room|bathroom|hall|cathedral|cave|arena|forest|custom"},
    {"room_size", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"damping", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"wet_db", ProtocolValueType::number, false, false, true, true, -80, 6, 0U, 0U, "", ""},
    {"pre_delay_ms", ProtocolValueType::number, false, false, true, true, 0, 250, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 14> fields_scene_set_music_player{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"attached", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"tracks", ProtocolValueType::string_array, false, false, false, false, 0, 0, 0U, 64U, "^[A-Za-z0-9_-][A-Za-z0-9._ /-]*\\.(wav|WAV|flac|FLAC|mp3|MP3|ogg|OGG)$", ""},
    {"bus", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"volume_db", ProtocolValueType::number, false, false, true, true, -80, 24, 0U, 0U, "", ""},
    {"crossfade_seconds", ProtocolValueType::number, false, false, true, true, 0, 30, 0U, 0U, "", ""},
    {"shuffle", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"loop_playlist", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"play_on_start", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"bpm", ProtocolValueType::number, false, false, true, true, 20, 400, 0U, 0U, "", ""},
    {"beats_per_bar", ProtocolValueType::integer, false, false, true, true, 1, 16, 0U, 0U, "", ""},
    {"first_beat_seconds", ProtocolValueType::number, false, false, true, true, 0, 60, 0U, 0U, "", ""},
    {"sync", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "immediate|beat|bar|track_end"},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_component_add{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"component", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "mesh_renderer|camera|light|collider|physics_body|joint|audio_source|audio_listener|reverb_zone|music_player|keyframes|script"},
    {"behaviour", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z_][A-Za-z0-9_]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_component_remove{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"component", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "mesh_renderer|camera|light|collider|physics_body|joint|audio_source|audio_listener|reverb_zone|music_player|keyframes|script"},
    {"index", ProtocolValueType::integer, false, false, true, true, 0, 31, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_scene_set_script{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"index", ProtocolValueType::integer, true, false, true, true, 0, 31, 0U, 0U, "", ""},
    {"behaviour", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z_][A-Za-z0-9_]*$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 9> fields_scene_set_script_property{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"index", ProtocolValueType::integer, true, false, true, true, 0, 31, 0U, 0U, "", ""},
    {"property", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z_][A-Za-z0-9_]*$", ""},
    {"number", ProtocolValueType::number, false, false, true, true, -1000000000000000.0, 1000000000000000.0, 0U, 0U, "", ""},
    {"boolean", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"text", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 1024U, "", ""},
    {"vector", ProtocolValueType::number_array, false, false, false, false, 0, 0, 3U, 3U, "", ""},
    {"reset", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_templates_instantiate{{
    {"template", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 80U, "^project:[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"parent", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"name", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_templates_save{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"replace", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 14> fields_scene_set_light{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "directional|point|spot"},
    {"red", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"green", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"blue", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"intensity", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"constant", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"linear", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"quadratic", ProtocolValueType::number, false, false, true, true, 0, 100000, 0U, 0U, "", ""},
    {"inner_cone", ProtocolValueType::number, false, false, true, true, 0, 1.5707963267948966, 0U, 0U, "", ""},
    {"outer_cone", ProtocolValueType::number, false, false, true, true, 0.0001, 1.5707963267948966, 0U, 0U, "", ""},
    {"range", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scene_rename{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 6> fields_scene_pick{{
    {"origin_x", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"origin_y", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"origin_z", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_x", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_y", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"direction_z", ProtocolValueType::number, true, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_bounds{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_save{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 12U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay\\.json$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_load{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 12U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay\\.json$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_trace_start{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay-trace\\.jsonl$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_trace_replay{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.relay-trace\\.jsonl$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_copy{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_cut{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_duplicate_many{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_destroy_many{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_scene_transform_many{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
    {"delta", ProtocolValueType::number_array, true, false, false, false, 0, 0, 16U, 16U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_scene_paste{{
    {"parent", ProtocolValueType::string, false, true, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_project_create{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_project_open{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_project_add_scene{{
    {"scene_file", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_project_remove_scene{{
    {"scene_file", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_project_set_startup{{
    {"scene_file", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_project_package{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 5U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.tar$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 12> fields_scene_keyframe_set{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"time_seconds", ProtocolValueType::number, true, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"px", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"py", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"pz", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"rx", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"ry", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"rz", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"sx", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"sy", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"sz", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_scene_keyframe_delete{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"time_seconds", ProtocolValueType::number, true, false, true, true, 0, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_scene_keyframes_playback{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"playing", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"loop", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"speed", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"duration_seconds", ProtocolValueType::number, false, false, true, true, 0.001, 1000000, 0U, 0U, "", ""},
    {"time_seconds", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 6> fields_scene_set_animations{{
    {"entities", ProtocolValueType::string_array, true, false, false, false, 0, 0, 1U, 4096U, "^\\d+:\\d+$", ""},
    {"playing", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"loop", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"speed", ProtocolValueType::number, false, false, true, true, -100, 100, 0U, 0U, "", ""},
    {"time_seconds", ProtocolValueType::number, false, false, true, true, 0, 1000000, 0U, 0U, "", ""},
    {"gesture", ProtocolValueType::integer, false, false, true, true, 0, 4294967295, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_animation_clip{{
    {"model", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 256U, "", ""},
    {"clip", ProtocolValueType::integer, true, false, true, true, 0, 255, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_session_audit{{
    {"after", ProtocolValueType::integer, false, false, true, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_session_request{{
    {"scope", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 64U, "", ""},
    {"kind", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "", "method|entity|file"},
    {"target", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_session_grant{{
    {"scope", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 64U, "", ""},
    {"kind", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "", "method|entity|file"},
    {"target", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_session_decide{{
    {"request", ProtocolValueType::integer, true, false, true, false, 0, 0, 0U, 0U, "", ""},
    {"allow", ProtocolValueType::boolean, true, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_session_revoke{{
    {"scope", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 64U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_session_export_audit{{
    {"filename", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 128U, "^[A-Za-z0-9][A-Za-z0-9._-]*\\.jsonl$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_chat_submit{{
    {"message", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 4000U, "", ""},
    {"attachments", ProtocolValueType::string_array, false, false, false, false, 0, 0, 0U, 8U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_bridge_publish{{
    {"view", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 65536U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_session_auto_approval{{
    {"enabled", ProtocolValueType::boolean, true, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 6> fields_chat_configure{{
    {"endpoint", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 2048U, "", ""},
    {"model", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 256U, "", ""},
    {"auth", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "bearer|header|none"},
    {"header", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 128U, "", ""},
    {"credential", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 4096U, "", ""},
    {"clear", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 4> fields_chat_control{{
    {"action", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "signin|cancel_signin|signout|refresh|select|new_chat|provider"},
    {"model", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 256U, "", ""},
    {"effort", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 32U, "", ""},
    {"provider", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "openai|compatible"},
}};

constexpr std::array<ProtocolFieldSpec, 7> fields_audio_set_bus{{
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"new_name", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"parent", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"volume_db", ProtocolValueType::number, false, false, true, true, -80, 24, 0U, 0U, "", ""},
    {"mute", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"solo", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"preview", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_audio_remove_bus{{
    {"name", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_audio_play{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_audio_stop{{
    {"entity", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"sound", ProtocolValueType::integer, false, false, true, true, 1, 1000000000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_audio_clip{{
    {"clip", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "^[A-Za-z0-9_-][A-Za-z0-9._ /-]*\\.(wav|WAV|flac|FLAC|mp3|MP3|ogg|OGG)$", ""},
    {"peaks", ProtocolValueType::integer, false, false, true, true, 0, 2048, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 24> fields_audio_set_effect{{
    {"bus", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"index", ProtocolValueType::integer, false, false, true, true, 0, 7, 0U, 0U, "", ""},
    {"type", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "reverb|delay|eq|compressor|limiter|lowpass|highpass"},
    {"enabled", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
    {"mix", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"room_size", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"damping", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"width", ProtocolValueType::number, false, false, true, true, 0, 1, 0U, 0U, "", ""},
    {"pre_delay_ms", ProtocolValueType::number, false, false, true, true, 0, 250, 0U, 0U, "", ""},
    {"time_ms", ProtocolValueType::number, false, false, true, true, 1, 2000, 0U, 0U, "", ""},
    {"feedback", ProtocolValueType::number, false, false, true, true, 0, 0.95, 0U, 0U, "", ""},
    {"low_db", ProtocolValueType::number, false, false, true, true, -24, 24, 0U, 0U, "", ""},
    {"mid_db", ProtocolValueType::number, false, false, true, true, -24, 24, 0U, 0U, "", ""},
    {"mid_frequency", ProtocolValueType::number, false, false, true, true, 100, 10000, 0U, 0U, "", ""},
    {"high_db", ProtocolValueType::number, false, false, true, true, -24, 24, 0U, 0U, "", ""},
    {"threshold_db", ProtocolValueType::number, false, false, true, true, -60, 0, 0U, 0U, "", ""},
    {"ratio", ProtocolValueType::number, false, false, true, true, 1, 20, 0U, 0U, "", ""},
    {"attack_ms", ProtocolValueType::number, false, false, true, true, 0.1, 500, 0U, 0U, "", ""},
    {"release_ms", ProtocolValueType::number, false, false, true, true, 1, 5000, 0U, 0U, "", ""},
    {"makeup_db", ProtocolValueType::number, false, false, true, true, 0, 24, 0U, 0U, "", ""},
    {"ceiling_db", ProtocolValueType::number, false, false, true, true, -24, 0, 0U, 0U, "", ""},
    {"cutoff_hz", ProtocolValueType::number, false, false, true, true, 20, 20000, 0U, 0U, "", ""},
    {"resonance", ProtocolValueType::number, false, false, true, true, 0.1, 10, 0U, 0U, "", ""},
    {"preview", ProtocolValueType::boolean, false, false, false, false, 0, 0, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 2> fields_audio_remove_effect{{
    {"bus", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"index", ProtocolValueType::integer, true, false, true, true, 0, 7, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 3> fields_audio_move_effect{{
    {"bus", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"index", ProtocolValueType::integer, true, false, true, true, 0, 7, 0U, 0U, "", ""},
    {"to", ProtocolValueType::integer, true, false, true, true, 0, 7, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 5> fields_audio_music{{
    {"entity", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "^\\d+:\\d+$", ""},
    {"action", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "play|next|stop"},
    {"track", ProtocolValueType::integer, false, false, true, true, 0, 63, 0U, 0U, "", ""},
    {"sync", ProtocolValueType::string, false, false, false, false, 0, 0, 0U, 0U, "", "immediate|beat|bar|track_end"},
    {"fade_seconds", ProtocolValueType::number, false, false, true, true, 0, 30, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 9> fields_audio_play_clip{{
    {"clip", ProtocolValueType::string, true, false, false, false, 0, 0, 1U, 128U, "^[A-Za-z0-9_-][A-Za-z0-9._ /-]*\\.(wav|WAV|flac|FLAC|mp3|MP3|ogg|OGG)$", ""},
    {"x", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"y", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"z", ProtocolValueType::number, false, false, true, true, -1000000, 1000000, 0U, 0U, "", ""},
    {"volume_db", ProtocolValueType::number, false, false, true, true, -80, 24, 0U, 0U, "", ""},
    {"pitch", ProtocolValueType::number, false, false, true, true, 0.1, 4, 0U, 0U, "", ""},
    {"bus", ProtocolValueType::string, false, false, false, false, 0, 0, 1U, 64U, "^[A-Za-z0-9_][A-Za-z0-9 _-]*$", ""},
    {"min_distance", ProtocolValueType::number, false, false, true, true, 0.01, 1000000, 0U, 0U, "", ""},
    {"max_distance", ProtocolValueType::number, false, false, true, true, 0.01, 1000000, 0U, 0U, "", ""},
}};

constexpr std::array<ProtocolFieldSpec, 1> fields_audio_set_spatialization{{
    {"mode", ProtocolValueType::string, true, false, false, false, 0, 0, 0U, 0U, "", "stereo|binaural"},
}};

constexpr std::array<ProtocolMethodSpec, 148> methods{{
    {"runtime.status", "runtime_status", "Inspect Relay runtime", "Read the current editor or game mode, pause, frame, simulation time and resolution state.", true, false, false, false, false, no_fields},
    {"runtime.play", "runtime_play", "Run game", "Start a temporary game session from the authored scene. Stop restores the authored scene and discards runtime changes.", false, false, false, false, false, no_fields},
    {"runtime.stop", "runtime_stop", "Stop game", "Stop the current game session and restore the authored scene without changing undo history.", false, false, false, false, false, no_fields},
    {"runtime.pause", "runtime_pause", "Pause Relay runtime", "Pause a running game so its scene can be inspected deterministically.", false, false, true, false, false, no_fields},
    {"runtime.resume", "runtime_resume", "Resume Relay runtime", "Resume a paused game after inspection or a controlled frame step.", false, false, true, false, false, no_fields},
    {"runtime.step", "runtime_step", "Step Relay frames", "Advance an exact number of deterministic game frames, including while paused.", false, false, false, false, false, fields_runtime_step},
    {"runtime.quit", "runtime_shutdown", "Shut down Relay runtime", "Request an orderly shutdown of the runtime owned by this MCP bridge.", false, false, true, false, false, no_fields},
    {"editor.camera.status", "editor_camera_status", "Inspect editor camera", "Read the live editor inspection viewpoint used by Vulkan captures. Unavailable without an editor. Does not modify scene cameras.", true, false, false, false, false, no_fields},
    {"editor.camera.set", "editor_camera_set", "Position editor inspection camera", "Set the live inspector camera target, orbit angles in radians and distance for visual confirmation using render_capture source vulkan. View-only: no scene or undo changes.", false, false, false, false, false, fields_editor_camera_set},
    {"editor.camera.frame", "editor_camera_frame", "Frame entity in inspection camera", "Frame an entity and its descendant bounds in the live inspection view before Vulkan capture. Does not change selection, scene cameras or undo history.", false, false, false, false, false, fields_editor_camera_frame},
    {"render.capture", "render_capture", "Capture Relay frame", "Save the current rendered frame in Relay's captures directory for visual inspection.", false, false, false, false, false, fields_render_capture},
    {"render.capture_async", "render_capture_async", "Queue Relay frame capture", "Capture real Vulkan or deterministic CPU frames through bounded background image workers.", false, false, false, false, false, fields_render_capture_async},
    {"render.capture_cancel", "render_capture_cancel", "Cancel pending capture", "Cancel a queued image or GPU readback job; writing and completed jobs cannot be cancelled. GPU slots remain alive until their fence completes.", false, false, false, false, false, fields_render_capture_cancel},
    {"render.capture_status", "render_capture_status", "Inspect capture job", "Check whether an asynchronous capture is queued, writing, complete or failed.", true, false, false, false, false, fields_render_capture_status},
    {"render.capabilities", "render_capabilities", "Inspect graphics capabilities", "Create a temporary Vulkan device and report adapter and modern rendering support.", true, false, false, false, false, no_fields},
    {"render.graph", "render_graph", "Inspect render graph", "Read compiled render passes, resources, dependencies and access transitions.", true, false, false, false, false, no_fields},
    {"render.shader_interfaces", "render_shader_interfaces", "Inspect shader interfaces", "Read SPIR-V-reflected stages, locations, descriptor bindings and push-constant sizes from the live Vulkan pipeline.", true, false, false, false, false, no_fields},
    {"render.upload_status", "render_upload_status", "Inspect upload memory", "Read Vulkan asset upload budgets, staging peaks, estimated resident bytes and transfer-path state.", true, false, false, false, false, no_fields},
    {"render.assets", "render_assets", "Inspect render assets", "List built-in and imported meshes, materials and textures currently available to scene renderer components.", true, false, false, false, false, no_fields},
    {"assets.formats", "asset_import_formats", "Inspect model import formats", "Report model formats and feature coverage available in this Relay build, including Godot-compatible interchange paths.", true, false, false, false, false, no_fields},
    {"assets.import_model", "asset_import_model", "Import project model", "Import a model from the project-local assets directory using a content-addressed identity and optionally instantiate its node hierarchy.", false, false, false, false, false, fields_assets_import_model},
    {"assets.browse", "asset_browse", "Browse project files", "List the folders and files in one project folder, folders first, with each entry's asset kind. Hidden entries, symlinks and .relayproject files are omitted; importable models are marked.", true, false, false, false, false, fields_assets_browse},
    {"assets.search", "asset_search", "Search project files", "Find project files and folders anywhere below the project root whose names contain the query, optionally limited to asset kinds. Hidden entries, symlinks and .relayproject files are skipped; at most 512 results.", true, false, false, false, false, fields_assets_search},
    {"assets.create_folder", "asset_create_folder", "Create project folder", "Create a new, empty folder inside an existing project folder.", false, false, false, false, false, fields_assets_create_folder},
    {"assets.move", "asset_move", "Rename or move project file", "Rename or move a project file or folder without overwriting. Import records follow moved models; project scene files and the project file cannot move.", false, false, false, false, false, fields_assets_move},
    {"assets.delete", "asset_delete", "Delete project file", "Move a project file or folder into the hidden .relay-trash folder, where it can be recovered by hand. Project scene files and the project file cannot be deleted.", false, true, false, false, false, fields_assets_delete},
    {"logs.read", "logs_read", "Read Relay logs", "Read structured engine log entries newer than a sequence number.", true, false, false, false, false, fields_logs_read},
    {"performance.read", "performance_read", "Read Relay performance", "Read bounded per-frame CPU/GPU timing, draw/resource counts, entities and process memory.", true, false, false, false, false, fields_performance_read},
    {"profiler.read", "profiler_read", "Read frame profile", "Find what limits the frame rate of the live editor or running game. Aggregates recent profiled frames into frame-time statistics, a CPU/GPU/display bottleneck verdict, a call tree of timed CPU scopes (simulation, scripts per behaviour, physics, rendering, editor UI and waits), hotspots by self time and per-pass GPU timings. Only a live editor records frames.", true, false, false, false, false, fields_profiler_read},
    {"profiler.set", "profiler_set", "Pause frame profiler", "Pause the frame profiler to keep its recorded frames for inspection, or resume recording. Clearing discards recorded frames.", false, false, true, false, false, fields_profiler_set},
    {"input.recent", "input_recent", "Read recent Relay input", "Read the bounded normalized keyboard, mouse and gamepad input event history.", true, false, false, false, false, no_fields},
    {"graphics.settings", "graphics_settings", "Read graphics settings", "Read the project's graphics settings (settings.graphics in the .relayproject): global illumination, ray traced reflections, vsync and the game's frame rate limit, with the defaults. When a live renderer is attached, also reports whether each effect is supported and running on this GPU and why not, and the presentation mode in use.", true, false, false, false, false, no_fields},
    {"graphics.set_settings", "graphics_set_settings", "Change graphics settings", "Turn global illumination, ray traced reflections or vsync on or off, or set the frame rate limit used while the game runs, and save the choice in the open project. Omitted settings keep their current values. Effects the GPU cannot run stay off and are reported by graphics.settings.", false, false, false, false, false, fields_graphics_set_settings},
    {"input.map", "input_map", "Read input map", "Read the project's input map: named actions bound to keys, mouse buttons or gamepad buttons, and axes built from button pairs or gamepad sticks. Also returns the engine defaults. Controls look like key:space, key:left_shift, mouse:left, gamepad:a or gamepad:leftx.", true, false, false, false, false, no_fields},
    {"input.set_map", "input_set_map", "Replace input map", "Validate, save in the project file (settings.input in the .relayproject) and apply a complete input map document (format relay.input, version 1) as returned by input.map.", false, true, false, false, false, fields_input_set_map},
    {"input.state", "input_state", "Inspect game input", "Read the current game step's input: each action's held and pressed state, each axis value, held controls and mouse movement.", true, false, false, false, false, no_fields},
    {"input.simulate", "input_simulate", "Simulate game input", "Hold an action, or set an axis value, for a number of game steps during Run Game, as if a player pressed it. Use it with runtime.step to play-test scripts.", false, false, false, false, false, fields_input_simulate},
    {"input.release", "input_release", "Release game input", "Host-only. Release every held control, used when the game viewport loses input focus.", false, false, false, true, false, no_fields},
    {"video.start", "video_start", "Start Relay video", "Record real Vulkan or deterministic CPU frames to WebM with explicit frame drops.", false, false, false, false, false, fields_video_start},
    {"video.capabilities", "video_capabilities", "Inspect video capabilities", "Report whether this Relay build found the FFmpeg WebM encoder.", true, false, false, false, false, no_fields},
    {"video.stop", "video_stop", "Stop Relay video", "Drain pending readbacks and start background WebM finalization; poll video.status for completion and errors.", false, false, false, false, false, no_fields},
    {"video.status", "video_status", "Inspect Relay video", "Read recording state, submitted frames and explicitly reported frame drops.", true, false, false, false, false, no_fields},
    {"scene.list", "scene_list", "List scene entities", "List every live entity with its name, parent and local transform.", true, false, false, false, false, no_fields},
    {"scene.inspect", "scene_inspect", "Inspect scene entity", "Inspect one entity using its stable generation-checked handle.", true, false, false, false, false, fields_scene_inspect},
    {"scene.create", "scene_create", "Create scene node", "Create a node, optionally of a node type from nodes.types (which gives it that type's components, inherited from its ancestors) and optionally parented to another live node.", false, false, false, false, false, fields_scene_create},
    {"scene.destroy", "scene_destroy", "Destroy scene entity", "Destroy an entity and its descendants as one undoable transaction.", false, true, false, false, false, fields_scene_destroy},
    {"scene.duplicate", "scene_duplicate", "Duplicate scene entity", "Copy an entity and its descendants beside the original as one undoable transaction. Components are preserved, a copied camera is never the active one, and a copy of a whole imported model drives its own animation.", false, false, false, false, false, fields_scene_duplicate},
    {"scene.clear", "scene_clear", "Clear the scene", "Destroy every entity as one undoable transaction, leaving an empty scene to start new work in.", false, true, false, false, false, no_fields},
    {"scene.set_transform", "scene_set_transform", "Set entity transform", "Update selected local position, Euler rotation or scale fields in one transaction.", false, false, false, false, false, fields_scene_set_transform},
    {"scene.set_camera", "scene_set_camera", "Configure entity camera", "Add, update or remove a perspective or orthographic camera; activating one deactivates the previous camera.", false, false, false, false, false, fields_scene_set_camera},
    {"scene.set_renderer", "scene_set_renderer", "Configure entity renderer", "Attach a registered built-in or imported mesh and material to an entity, or remove its renderer component.", false, false, false, false, false, fields_scene_set_renderer},
    {"scene.set_parent", "scene_set_parent", "Set entity parent", "Reparent an entity safely; use null to move it to the scene root.", false, false, false, false, false, fields_scene_set_parent},
    {"scene.undo", "scene_undo", "Undo scene change", "Undo the most recent scene transaction and restore exact entity generations.", false, false, false, false, false, no_fields},
    {"scene.redo", "scene_redo", "Redo scene change", "Reapply the most recently undone scene transaction.", false, false, false, false, false, no_fields},
    {"scene.set_animation", "scene_set_animation", "Control imported animation", "Configure clip, playback, looping, speed and seek time on an imported model root.", false, false, false, false, false, fields_scene_set_animation},
    {"scene.set_morph", "scene_set_morph", "Set imported morph weight", "Override a mesh morph weight, or reset all overrides to imported defaults and animation.", false, false, false, false, false, fields_scene_set_morph},
    {"scene.set_collider", "scene_set_collider", "Configure collider", "Add, edit or remove an authored box, sphere, capsule, convex or triangle-mesh collider. Sphere and capsule use the largest world scale uniformly. Convex and mesh shapes use a registered mesh, defaulting to the entity renderer mesh. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_set_collider},
    {"physics.raycast", "physics_raycast", "Raycast colliders", "Find the nearest enabled authored collider of any shape hit by a world-space ray. Returns hit point and surface normal; does not move objects.", true, false, false, false, false, fields_physics_raycast},
    {"physics.overlaps", "physics_overlaps", "Find overlapping colliders", "List up to 128 enabled colliders of any shape overlapping an entity collider. Both colliders must pass their layer masks; reports truncation. Triangle-mesh colliders report surface contact only.", true, false, false, false, false, fields_physics_overlaps},
    {"physics.debug_boxes", "physics_debug_boxes", "Inspect collider wireframes", "Read bounded world-space collider outlines for the editor overlay, including disabled colliders.", true, false, false, true, false, no_fields},
    {"physics.body_status", "physics_body_status", "Inspect physics body", "Read the current linear and angular velocities of a dynamic body during Run Game.", true, false, false, false, false, fields_physics_body_status},
    {"physics.contact_events", "physics_contact_events", "Read collision contacts", "Read bounded contact begin and end events from the current game session, using a sequence cursor. Events are cleared on Stop Game.", true, false, false, false, false, fields_physics_contact_events},
    {"physics.apply_impulse", "physics_apply_impulse", "Apply rigid body impulse", "Apply a world-space impulse to a dynamic body during Run Game. Optional world-space point produces torque and angular motion.", false, false, false, false, false, fields_physics_apply_impulse},
    {"scene.set_physics_body", "scene_set_physics_body", "Configure physics body", "Add, edit or remove an undoable static or dynamic physics body. Dynamic bodies use Jolt rigid-body collision, gravity and angular dynamics during Run Game.", false, false, false, false, false, fields_scene_set_physics_body},
    {"scripts.status", "scripts_status", "Inspect gameplay scripts", "Read native C++ script state: project trust, build state, whether sources changed since the last build, registered behaviours, compiler diagnostics with file and line, and runtime errors from behaviour callbacks.", true, false, false, false, false, no_fields},
    {"scripts.build", "scripts_build", "Build gameplay scripts", "Compile the project's scripts/ C++ files into a native library in the background; unchanged files are reused. Poll scripts.status until the state is ready or failed. A build that finishes during Run Game hot reloads the running behaviours. Requires a project a person has trusted.", false, false, false, false, false, no_fields},
    {"scripts.trust", "scripts_trust", "Trust project scripts", "Host-only. Allow or forbid building and running this project's native C++ scripts, which run with the editor's full privileges. Stored per user, outside the project.", false, false, false, true, false, fields_scripts_trust},
    {"scripts.sdk", "scripts_sdk", "Read script SDK", "Return relay_script.hpp, the complete C++ API available to gameplay scripts, with usage notes and frame order. Read it before writing a script.", true, false, false, false, false, no_fields},
    {"scripts.read", "scripts_read", "Read script source", "Read a C++ source or header from the project's scripts/ folder.", true, false, false, false, false, fields_scripts_read},
    {"scripts.write", "scripts_write", "Write script source", "Create or replace a C++ source or header in the project's scripts/ folder, creating subfolders. Allowed during Run Game; build afterwards to compile it or hot reload it.", false, true, false, false, false, fields_scripts_write},
    {"scripts.create", "scripts_create", "Create behaviour script", "Create scripts/<behaviour>.cpp from a starter template defining and registering that behaviour class. Refuses to overwrite.", false, false, false, false, false, fields_scripts_create},
    {"component.types", "component_types", "List component types", "List every component a node can carry: engine components with their category and whether they can be added, removed or repeated, plus each built script behaviour with its declared properties and code defaults.", true, false, false, false, false, no_fields},
    {"scene.set_joint", "scene_set_joint", "Configure joint", "Add, edit or remove an undoable joint linking this node's physics body to another node's body, or to the world when connected is empty, during Run Game. Types: fixed (weld), point (ball and socket), hinge (turns about axis, optional angle limits in degrees with min in [-180, 0] and max in [0, 180], optional motor), slider (moves along axis, optional travel limits in metres with min <= 0 <= max, optional motor) and distance (rope or spring between anchor and connected_anchor; limits are lengths, otherwise the starting length is kept). Anchor and axis are in this node's local space; connected_anchor is in the connected node's space, or world space for the world. At least one body must be dynamic. Joined bodies do not collide unless collide_connected is set. Changing type resets the limits to that type's defaults unless limits are given too.", false, false, false, false, false, fields_scene_set_joint},
    {"scene.set_audio_source", "scene_set_audio_source", "Configure audio source", "Add, edit or remove a node's audio source: a project sound file (.wav, .flac, .mp3 or .ogg) played through a mixer bus during Run Game. Spatial sources fade with distance from the listener (inverse, inverse square or linear rolloff between the minimum and maximum distance), pan around it and shift pitch with relative motion (doppler); flat sources play as stereo with a balance. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_set_audio_source},
    {"scene.set_reverb_zone", "scene_set_reverb_zone", "Configure reverb zone", "Add, edit or remove a reverb zone: a sphere or box (following the node's position, rotation and scale) where spatial sounds take on a room's reverb while the listener is inside, fading out over fade metres outside it. Choosing a preset (room, small_room, bathroom, hall, cathedral, cave, arena, forest) sets its parameters; changing a parameter makes the zone custom. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_set_reverb_zone},
    {"scene.set_music_player", "scene_set_music_player", "Configure music player", "Add, edit or remove a music player: a playlist of project sound files played flat on a bus during Run Game, one after another with a crossfade, optionally shuffled and looping. Long files stream. Changes asked for with audio.music wait for the player's sync point (immediate, beat, bar or track_end) counted at bpm from first_beat_seconds. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_set_music_player},
    {"component.add", "component_add", "Add component", "Add an engine component with editor defaults, or append a script component running a behaviour, as one undoable transaction. Configure it afterwards with the component's own method, such as scene.set_camera or scene.set_script_property.", false, false, false, false, false, fields_component_add},
    {"component.remove", "component_remove", "Remove component", "Remove one component as an undoable transaction. The Transform and imported model animation cannot be removed.", false, true, false, false, false, fields_component_remove},
    {"scene.set_script", "scene_set_script", "Configure script component", "Change the behaviour or enabled state of one of a node's script components, as an undoable transaction.", false, false, false, false, false, fields_scene_set_script},
    {"scene.set_script_property", "scene_set_script_property", "Set script property", "Store a value for a behaviour property on one script component, or reset it to the code default. Send exactly one of number, boolean, text or vector unless resetting.", false, false, false, false, false, fields_scene_set_script_property},
    {"nodes.types", "nodes_types", "List node types", "List the node type tree. Each type adds components to its parent's; creatable types can be passed to scene.create. A node's reported type is the deepest type whose components it has.", true, false, false, false, false, no_fields},
    {"templates.list", "templates_list", "List node templates", "List the project's saved templates (prefabs) with the node type each root inherits and the root's components and script behaviours. Built-in node types are listed by nodes.types.", true, false, false, false, false, no_fields},
    {"templates.instantiate", "templates_instantiate", "Create node from template", "Create a saved node tree from a project template as one undoable transaction and return its root. The result is an independent copy.", false, false, false, false, false, fields_templates_instantiate},
    {"templates.save", "templates_save", "Save node as template", "Save a node and its children as a project template in templates/<name>.relay-template.json, usable from the Create menu and templates.instantiate.", false, true, false, false, false, fields_templates_save},
    {"scene.set_light", "scene_set_light", "Configure scene light", "Add, update or remove a directional, point or spot light.", false, false, false, false, false, fields_scene_set_light},
    {"scene.rename", "scene_rename", "Rename scene entity", "Change an entity's display name as one undoable transaction.", false, false, false, false, false, fields_scene_rename},
    {"scene.history", "scene_history", "Inspect undo history", "Read the labels currently on the undo and redo stacks, newest first.", true, false, false, false, false, no_fields},
    {"assets.available", "asset_available_models", "List importable models", "List model files present in the project assets directory that this build can import. Top-level files only; the import sandbox is unchanged.", true, false, false, false, false, no_fields},
    {"scene.pick", "scene_pick", "Pick scene entity", "Find the nearest drawable entity a world-space ray enters. Bounds-level precision, not per-triangle. Stateless: the caller supplies the ray, so the engine stores no viewpoint.", true, false, false, false, false, fields_scene_pick},
    {"scene.bounds", "scene_bounds", "Inspect entity bounds", "Read the world-space axis-aligned bounds and origin of an entity and its descendants, for framing a selection or locating an object.", true, false, false, false, false, fields_scene_bounds},
    {"scene.snapshot", "scene_snapshot", "Snapshot Relay scene", "Return deterministic scene JSON plus reflected component field metadata.", true, false, false, false, false, no_fields},
    {"scene.save", "scene_save", "Save Relay scene", "Atomically save the current scene in Relay's project-local scenes directory.", false, true, true, false, false, fields_scene_save},
    {"scene.load", "scene_load", "Load Relay scene", "Validate, migrate and load a project scene as one undoable transaction.", false, false, false, false, false, fields_scene_load},
    {"trace.start", "trace_start", "Start Relay trace", "Record frame-stamped agent commands and normalized human input events.", false, false, false, false, false, fields_trace_start},
    {"trace.stop", "trace_stop", "Stop Relay trace", "Atomically persist the active deterministic trace in Relay's traces directory.", false, false, false, false, false, no_fields},
    {"trace.status", "trace_status", "Inspect Relay trace", "Read trace recording state, path and current event count.", true, false, false, false, false, no_fields},
    {"trace.replay", "trace_replay", "Replay Relay trace", "Validate and replay a trace against the fixed-step runtime at its recorded frame offsets.", false, false, false, false, false, fields_trace_replay},
    {"scene.copy", "scene_copy", "Copy", "Copy selected subtrees to the session clipboard without changing the scene.", false, false, false, false, false, fields_scene_copy},
    {"scene.cut", "scene_cut", "Cut", "Copy and remove selected subtrees as one undoable edit.", false, true, false, false, false, fields_scene_cut},
    {"scene.duplicate_many", "scene_duplicate_many", "Duplicate Many", "Duplicate selected subtrees beside their originals as one undoable edit.", false, false, false, false, false, fields_scene_duplicate_many},
    {"scene.destroy_many", "scene_destroy_many", "Destroy Many", "Remove selected subtrees as one undoable edit.", false, true, false, false, false, fields_scene_destroy_many},
    {"scene.transform_many", "scene_transform_many", "Transform Many", "Apply a column-major world-space affine delta matrix to selected roots as one undoable gesture.", false, false, false, false, false, fields_scene_transform_many},
    {"scene.paste", "scene_paste", "Paste entities", "Paste the session clipboard as one undoable edit; cameras stay inactive and internal model bindings are remapped.", false, false, false, false, false, fields_scene_paste},
    {"scene.clipboard", "scene_clipboard", "Inspect clipboard", "Read session clipboard root and entity counts.", true, false, false, false, false, no_fields},
    {"project.create", "project_create", "Create project", "Create a folder project (.relayproject) and an empty scene; refuses to overwrite an existing project.", false, false, false, false, false, fields_project_create},
    {"project.open", "project_open", "Open project", "Open a folder project (.relayproject) and load its startup scene atomically, or clear the scene for an empty project.", false, false, false, false, false, fields_project_open},
    {"project.status", "project_status", "Status project", "Inspect the current project, member scene files and startup scene.", true, false, false, false, false, no_fields},
    {"project.list", "project_list", "List project", "List available workspace project files.", true, false, false, false, false, no_fields},
    {"project.add_scene", "project_add_scene", "Add Scene project", "Add an existing valid scene file to the current project; the first scene becomes its startup scene.", false, false, false, false, false, fields_project_add_scene},
    {"project.remove_scene", "project_remove_scene", "Remove Scene project", "Remove scene membership without deleting its file; chooses a remaining startup scene when needed.", false, false, false, false, false, fields_project_remove_scene},
    {"project.set_startup", "project_set_startup", "Set Startup project", "Choose a current project member as the startup scene.", false, false, false, false, false, fields_project_set_startup},
    {"project.close", "project_close", "Close project", "Close project metadata while leaving the current scene intact.", false, false, false, false, false, no_fields},
    {"project.package", "project_package", "Package project", "Export saved project metadata, member scenes and non-hidden assets as a portable uncompressed tar under the project exports directory. Refuses to overwrite; save scene changes first.", false, false, false, false, false, fields_project_package},
    {"scene.keyframe.set", "scene_keyframe_set", "Set transform keyframe", "Add or update a scene-owned transform keyframe at an exact time. Unspecified transform fields use the current entity transform or existing key. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_keyframe_set},
    {"scene.keyframe.delete", "scene_keyframe_delete", "Delete transform keyframe", "Remove one scene-owned transform keyframe at an exact time as an undoable edit.", false, false, false, false, false, fields_scene_keyframe_delete},
    {"scene.keyframes.playback", "scene_keyframes_playback", "Control transform keyframes", "Set playback, loop, speed, duration or current time for scene-owned transform keys. Undoable and saved with the scene.", false, false, false, false, false, fields_scene_keyframes_playback},
    {"scene.set_animations", "scene_set_animations", "Control animation tracks", "Seek or configure multiple animation roots in one undoable gesture; time clamps to each clip duration.", false, false, false, false, false, fields_scene_set_animations},
    {"animation.clip", "animation_clip", "Inspect animation timeline", "Read bounded channel key times for an imported animation clip. Key times are read-only; truncated channels report their full key count.", true, false, false, false, false, fields_animation_clip},
    {"session.status", "session_status", "Inspect session grants", "Inspect exact native method grants for this connection. Grants are approved only by the host; no tool can expand them.", true, false, false, false, false, no_fields},
    {"session.audit", "session_audit", "Inspect session audit", "Read bounded session action decisions and outcomes. Scope is the exact native method. Oldest sequence exposes eviction; parameters are not retained.", true, false, false, false, false, fields_session_audit},
    {"session.request", "session_request", "Session request", "Request host approval for an exact method and optional entity/file target. This never grants access or executes an action.", false, false, false, false, false, fields_session_request},
    {"session.review", "session_review", "Session review", "Inspect pending requests, active scoped grants and native action descriptions.", true, false, false, true, false, no_fields},
    {"session.grant", "session_grant", "Session grant", "Host approval of an exact method scope bound to the current project.", false, false, false, true, false, fields_session_grant},
    {"session.decide", "session_decide", "Session decide", "Host approval or denial of a pending request. Stale project requests cannot be approved.", false, false, false, true, false, fields_session_decide},
    {"session.revoke", "session_revoke", "Session revoke", "Host revocation of all grants or one exact method.", false, false, false, true, false, fields_session_revoke},
    {"session.export_audit", "session_export_audit", "Session export_audit", "Export a bounded audit snapshot atomically under .relay/audits without overwriting existing records.", false, false, false, true, false, fields_session_export_audit},
    {"chat.submit", "chat_submit", "Chat submit", "Submit a user message to the external bridge. Providers and canonical conversation history remain outside the engine.", false, false, false, true, false, fields_chat_submit},
    {"chat.status", "chat_status", "Chat status", "Inspect the bounded external bridge display and pending user-message count.", true, false, false, true, false, no_fields},
    {"bridge.poll", "bridge_poll", "Bridge poll", "Consume bounded user-message submissions for the authenticated external bridge.", false, false, false, false, true, no_fields},
    {"bridge.publish", "bridge_publish", "Bridge publish", "Publish a bounded display snapshot from the authenticated external bridge.", false, false, false, false, true, fields_bridge_publish},
    {"chat.cancel", "chat_cancel", "Stop chat work", "Cancel pending chat submissions and ask the external bridge to abort its active turn. Completed native actions remain undoable.", false, false, false, true, false, no_fields},
    {"session.auto_approval", "session_auto_approval", "Auto approval", "Set full session access to every public engine action without approval prompts. Trusted host only.", false, false, false, true, false, fields_session_auto_approval},
    {"chat.configure", "chat_configure", "Configure chat provider", "Pass transient provider settings to the external bridge for private storage. Never traced or exposed to agent tools.", false, false, false, true, false, fields_chat_configure},
    {"chat.control", "chat_control", "Control agent harness", "Host-only OpenAI sign-in, account, model, reasoning and conversation controls, processed by the external bridge.", false, false, false, true, false, fields_chat_control},
    {"audio.status", "audio_status", "Inspect audio", "Read the audio output device, the listener, every playing voice (clip, bus, position, gains) and each mixer bus with its post-fader peak and RMS levels in dB.", true, false, false, false, false, no_fields},
    {"audio.settings", "audio_settings", "Read mixer buses", "Read the project's mixer buses (settings.audio in the .relayproject): name, parent, volume in dB, mute and solo, with the defaults.", true, false, false, false, false, no_fields},
    {"audio.set_bus", "audio_set_bus", "Create or change a mixer bus", "Create a bus, or change one's name, parent, volume, mute or solo, and save the mixer in the open project. A new bus defaults to Master as its parent. While any bus is soloed only soloed buses, their parents and their children are heard. Renaming keeps children attached; sources naming the old bus fall back to Master until they are changed.", false, false, false, false, false, fields_audio_set_bus},
    {"audio.remove_bus", "audio_remove_bus", "Remove a mixer bus", "Remove a bus other than Master and save the mixer; its children move to its parent and sources routed to it play into Master.", false, true, false, false, false, fields_audio_remove_bus},
    {"audio.play", "audio_play", "Play an audio source", "Start or restart a node's audio source. During Run Game it plays as authored; in the editor it plays as a flat preview.", false, false, false, false, false, fields_audio_play},
    {"audio.stop", "audio_stop", "Stop audio", "Stop a node's audio source, a one-shot by the handle audio.play_clip returned, or every playing sound when neither is given.", false, false, false, false, false, fields_audio_stop},
    {"audio.clip", "audio_clip", "Inspect a sound file", "Decode a project sound file and report its duration, sample rate, channels and frames, with optional min/max peak pairs across it for drawing a waveform.", true, false, false, false, false, fields_audio_clip},
    {"audio.set_effect", "audio_set_effect", "Add or change a bus effect", "Add an effect to a mixer bus's chain (omit index), or change the effect at index, and save the mixer in the open project. Types and their parameters: reverb (room_size, damping, width, pre_delay_ms, mix), delay (time_ms, feedback, damping, mix), eq (low_db shelf at 200 Hz, mid_db at mid_frequency, high_db shelf at 5 kHz), compressor (threshold_db, ratio, attack_ms, release_ms, makeup_db), limiter (ceiling_db, release_ms), lowpass and highpass (cutoff_hz, resonance). Effects run in order before the bus volume; at most 8 per bus.", false, false, false, false, false, fields_audio_set_effect},
    {"audio.remove_effect", "audio_remove_effect", "Remove a bus effect", "Remove the effect at index from a bus's chain and save the mixer.", false, true, false, false, false, fields_audio_remove_effect},
    {"audio.move_effect", "audio_move_effect", "Reorder a bus effect", "Move the effect at index to position to in the same bus's chain and save the mixer.", false, false, false, false, false, fields_audio_move_effect},
    {"audio.debug_shapes", "audio_debug_shapes", "Inspect audio shapes", "Read reverb zones (centre, box edge vectors or sphere radius in world space, fade) and spatial sources (centre, minimum and maximum distance) for drawing them in a viewport.", true, false, false, false, false, no_fields},
    {"audio.music", "audio_music", "Control a music player", "During Run Game: play a track (by playlist index), go to the next one, or stop with a fade. A change crossfades from the current track and lands on the next beat, bar or track end, or at once, as sync says (the player's own setting when omitted).", false, false, false, false, false, fields_audio_music},
    {"audio.play_clip", "audio_play_clip", "Play a sound file", "Play a project sound file once without a node: placed at x, y, z in the world during Run Game (flat in the editor, where it previews), or flat when no position is given. Returns a handle for audio.stop.", false, false, false, false, false, fields_audio_play_clip},
    {"audio.set_spatialization", "audio_set_spatialization", "Choose speakers or headphones", "Set how positioned sounds reach the ears and save it in the open project: stereo panning for speakers, or binaural for headphones, where a head model gives each ear its own delay and shadow and sounds behind are slightly duller.", false, false, false, false, false, fields_audio_set_spatialization},
}};

} // namespace

std::span<const ProtocolMethodSpec> protocol_methods() { return methods; }

const ProtocolMethodSpec* find_protocol_method(const std::string_view method) {
    const auto found = std::find_if(methods.begin(), methods.end(), [method](const auto& candidate) {
        return candidate.method == method;
    });
    return found == methods.end() ? nullptr : &*found;
}

} // namespace relay
