// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
#pragma once

#include <cstddef>
#include <span>
#include <string>
#include <string_view>

namespace relay {

inline constexpr unsigned protocol_schema_version = 19U;

enum class ProtocolValueType { string, integer, number, boolean, string_array, number_array };

struct ProtocolFieldSpec {
    std::string_view name;
    ProtocolValueType type;
    bool required;
    bool nullable;
    bool has_minimum;
    bool has_maximum;
    double minimum;
    double maximum;
    std::size_t minimum_length;
    std::size_t maximum_length;
    std::string_view pattern;
    std::string_view enum_values;
};

struct ProtocolMethodSpec {
    std::string_view method;
    std::string_view tool;
    std::string_view title;
    std::string_view description;
    bool read_only;
    bool destructive;
    bool idempotent;
    bool host_only;
    bool bridge_only;
    std::span<const ProtocolFieldSpec> fields;
};

[[nodiscard]] std::span<const ProtocolMethodSpec> protocol_methods();
[[nodiscard]] const ProtocolMethodSpec* find_protocol_method(std::string_view method);
[[nodiscard]] bool validate_protocol_request(std::string_view request, std::string_view method,
                                             std::string& error);

} // namespace relay
