#!/usr/bin/env python3
"""Generate Relay's native catalog, MCP registrations and protocol reference."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "protocol" / "relay.protocol.json"
HEADER_PATH = ROOT / "include" / "relay" / "control" / "generated_protocol.hpp"
CPP_PATH = ROOT / "src" / "control" / "generated_protocol.cpp"
TS_PATH = ROOT / "tools" / "mcp-bridge" / "src" / "generated_protocol.ts"
DOC_PATH = ROOT / "docs" / "protocol.md"


def cpp_string(value: str) -> str:
    return json.dumps(value).replace("\\/", "/")


def symbol(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value)


def boolean(value: bool) -> str:
    return "true" if value else "false"


def validate_schema(schema: dict) -> None:
    if (schema.get("format") != "relay.protocol" or
            not isinstance(schema.get("version"), int) or schema["version"] < 1):
        raise ValueError("unsupported protocol schema header")
    methods = schema.get("methods")
    if not isinstance(methods, list) or not methods:
        raise ValueError("methods must be a non-empty array")
    method_names: set[str] = set()
    tool_names: set[str] = set()
    for method in methods:
        for key in ("method", "tool", "title", "description", "params"):
            if key not in method:
                raise ValueError(f"method is missing {key}")
        if method["method"] in method_names or method["tool"] in tool_names:
            raise ValueError(f"duplicate method or tool: {method['method']}")
        method_names.add(method["method"])
        tool_names.add(method["tool"])
        wire_names: set[str] = set()
        input_names: set[str] = set()
        for field in method["params"]:
            if field.get("type") not in {"string", "integer", "number", "boolean", "string_array", "number_array"}:
                raise ValueError(f"unsupported field type in {method['method']}")
            input_name = field["name"]
            wire_name = field.get("wire", input_name)
            if input_name in input_names or wire_name in wire_names:
                raise ValueError(f"duplicate parameter in {method['method']}")
            input_names.add(input_name)
            wire_names.add(wire_name)


def generate_header(schema: dict) -> str:
    return f'''// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
#pragma once

#include <cstddef>
#include <span>
#include <string>
#include <string_view>

namespace relay {{

inline constexpr unsigned protocol_schema_version = {schema["version"]}U;

enum class ProtocolValueType {{ string, integer, number, boolean, string_array, number_array }};

struct ProtocolFieldSpec {{
    std::string_view name;
    ProtocolValueType type;
    bool required;
    bool nullable;
    bool has_minimum;
    bool has_maximum;
    double minimum;
    double maximum;
    std::size_t minimum_length;
    std::size_t maximum_length;
    std::string_view pattern;
    std::string_view enum_values;
}};

struct ProtocolMethodSpec {{
    std::string_view method;
    std::string_view tool;
    std::string_view title;
    std::string_view description;
    bool read_only;
    bool destructive;
    bool idempotent;
    std::span<const ProtocolFieldSpec> fields;
}};

[[nodiscard]] std::span<const ProtocolMethodSpec> protocol_methods();
[[nodiscard]] const ProtocolMethodSpec* find_protocol_method(std::string_view method);
[[nodiscard]] bool validate_protocol_request(std::string_view request, std::string_view method,
                                             std::string& error);

}} // namespace relay
'''


def generate_cpp(schema: dict) -> str:
    arrays: list[str] = []
    method_rows: list[str] = []
    type_names = {"string": "string", "integer": "integer", "number": "number", "boolean": "boolean", "string_array": "string_array", "number_array": "number_array"}
    for method in schema["methods"]:
        array_name = f"fields_{symbol(method['method'])}"
        params = method["params"]
        if params:
            rows = []
            for field in params:
                wire = field.get("wire", field["name"])
                enum_values = "|".join(field.get("enum", []))
                rows.append(
                    "    {" + ", ".join([
                        cpp_string(wire),
                        f"ProtocolValueType::{type_names[field['type']]}",
                        boolean(field.get("required", False)),
                        boolean(field.get("nullable", False)),
                        boolean("minimum" in field),
                        boolean("maximum" in field),
                        str(field.get("minimum", 0)),
                        str(field.get("maximum", 0)),
                        f"{field.get('minimumLength', 0)}U",
                        f"{field.get('maximumLength', 0)}U",
                        cpp_string(field.get("wirePattern", field.get("pattern", ""))),
                        cpp_string(enum_values),
                    ]) + "},"
                )
            arrays.append(
                f"constexpr std::array<ProtocolFieldSpec, {len(params)}> {array_name}{{{{\n"
                + "\n".join(rows) + "\n}};"
            )
            span = array_name
        else:
            span = "no_fields"
        method_rows.append(
            "    {" + ", ".join([
                cpp_string(method["method"]), cpp_string(method["tool"]),
                cpp_string(method["title"]), cpp_string(method["description"]),
                boolean(method.get("readOnly", False)), boolean(method.get("destructive", False)),
                boolean(method.get("idempotent", False)), span,
            ]) + "},"
        )
    return '''// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
#include "relay/control/generated_protocol.hpp"

#include <algorithm>
#include <array>

namespace relay {
namespace {

constexpr std::array<ProtocolFieldSpec, 0> no_fields{};

''' + "\n\n".join(arrays) + '''

constexpr std::array<ProtocolMethodSpec, ''' + str(len(schema["methods"])) + '''> methods{{
''' + "\n".join(method_rows) + '''
}};

} // namespace

std::span<const ProtocolMethodSpec> protocol_methods() { return methods; }

const ProtocolMethodSpec* find_protocol_method(const std::string_view method) {
    const auto found = std::find_if(methods.begin(), methods.end(), [method](const auto& candidate) {
        return candidate.method == method;
    });
    return found == methods.end() ? nullptr : &*found;
}

} // namespace relay
'''


def zod_expression(field: dict) -> str:
    field_type = field["type"]
    if field_type in {"string_array", "number_array"}:
        item = "z.string()" if field_type == "string_array" else "z.number().finite()"
        if field_type == "string_array" and "pattern" in field:
            item += f".regex(new RegExp({json.dumps(field['pattern'])}))"
        expression = f"z.array({item})"
        if "minimumLength" in field:
            expression += f".min({field['minimumLength']})"
        if "maximumLength" in field:
            expression += f".max({field['maximumLength']})"
    elif field_type == "string":
        expression = "z.string()"
        if "minimumLength" in field:
            expression += f".min({field['minimumLength']})"
        if "maximumLength" in field:
            expression += f".max({field['maximumLength']})"
        if "pattern" in field:
            expression += f".regex(new RegExp({json.dumps(field['pattern'])}))"
        if "enum" in field:
            expression = "z.enum([" + ", ".join(json.dumps(v) for v in field["enum"]) + "])"
    elif field_type in {"integer", "number"}:
        expression = "z.number()"
        if field_type == "integer":
            expression += ".int()"
        else:
            expression += ".finite()"
        if "minimum" in field:
            expression += f".min({field['minimum']})"
        if "maximum" in field:
            expression += f".max({field['maximum']})"
    else:
        expression = "z.boolean()"
    if field.get("nullable"):
        expression += ".nullable()"
    if "default" in field:
        expression += f".default({json.dumps(field['default'])})"
    elif not field.get("required"):
        expression += ".optional()"
    if field.get("description"):
        expression += f".describe({json.dumps(field['description'])})"
    return expression


def generate_ts(schema: dict) -> str:
    registrations: list[str] = []
    for method in schema["methods"]:
        params = method["params"]
        schema_fields = ",\n        ".join(
            f"{json.dumps(field['name'])}: {zod_expression(field)}" for field in params
        )
        input_schema = "z.object({" + ("\n        " + schema_fields + "\n      " if params else "") + "})"
        annotations = {
            "readOnlyHint": method.get("readOnly", False),
            "destructiveHint": method.get("destructive", False),
            "openWorldHint": False,
        }
        if method.get("idempotent"):
            annotations["idempotentHint"] = True
        annotation_text = json.dumps(annotations, separators=(",", ":")).replace('"', '')
        if params:
            mappings = ", ".join(
                f"{json.dumps(field.get('wire', field['name']))}: input[{json.dumps(field['name'])}]"
                for field in params
            )
            callback = f'''async (input) => {{
        const override = overrides[{json.dumps(method["tool"])}];
        if (override) return override(input as JsonObject);
        return invoke({json.dumps(method["method"])}, {{{mappings}}});
      }}'''
        else:
            callback = f'''async () => {{
        const override = overrides[{json.dumps(method["tool"])}];
        if (override) return override({{}});
        return invoke({json.dumps(method["method"])}, {{}});
      }}'''
        registrations.append(f'''  server.registerTool(
    {json.dumps(method["tool"])},
    {{
      title: {json.dumps(method["title"])},
      description: {json.dumps(method["description"])},
      inputSchema: {input_schema},
      annotations: {annotation_text},
    }},
    {callback},
  );''')
    return '''// Generated by tools/generate_protocol.py from protocol/relay.protocol.json. Do not edit.
import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";

export type JsonObject = Record<string, unknown>;
export type ToolResponse = any;
export type GeneratedInvoke = (method: string, parameters: JsonObject) => Promise<ToolResponse>;
export type GeneratedOverride = (input: JsonObject) => Promise<ToolResponse>;

export function registerGeneratedTools(
  server: McpServer,
  invoke: GeneratedInvoke,
  overrides: Record<string, GeneratedOverride> = {},
): void {
''' + "\n\n".join(registrations) + '''
}
'''


def generate_docs(schema: dict) -> str:
    lines = [
        "<!-- Generated by tools/generate_protocol.py. Do not edit. -->",
        "# Relay protocol reference",
        "",
        f"Schema version: `{schema['version']}` · Native methods: `{len(schema['methods'])}` · MCP tools: `{len(schema['methods'])}`",
        "",
        "| Native method | MCP tool | Parameters | Access | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for method in schema["methods"]:
        params = []
        for field in method["params"]:
            label = f"`{field['name']}`: {field['type']}"
            if field.get("nullable"):
                label += " or null"
            if field.get("required"):
                label += " (required)"
            elif "default" in field:
                label += f" = `{json.dumps(field['default'], separators=(',', ':'))}`"
            params.append(label)
        access = "read-only" if method.get("readOnly") else "mutating"
        if method.get("destructive"):
            access += ", destructive"
        lines.append(
            f"| `{method['method']}` | `{method['tool']}` | {'<br>'.join(params) if params else '—'} | {access} | {method['description']} |"
        )
    lines += [
        "",
        "## Generation",
        "",
        "Edit `protocol/relay.protocol.json`, then run `python3 tools/generate_protocol.py`.",
        "Use `python3 tools/generate_protocol.py --check` in CI to reject stale generated artifacts.",
        "",
    ]
    return "\n".join(lines)


def write_or_check(path: pathlib.Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    validate_schema(schema)
    outputs = {
        HEADER_PATH: generate_header(schema),
        CPP_PATH: generate_cpp(schema),
        TS_PATH: generate_ts(schema),
        DOC_PATH: generate_docs(schema),
    }
    stale = [path for path, content in outputs.items() if not write_or_check(path, content, arguments.check)]
    if stale:
        print("Generated protocol artifacts are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if not arguments.check:
        for path in outputs:
            print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
