#!/usr/bin/env python3
"""Generates src/render/blue_noise_data.inc: a 128x128 two-channel blue noise texture.

Each channel is an independent void-and-cluster rank map (Ulichney 1993), quantised to 8 bits.
Global illumination sampling reads it; the renderer derives per-frame variants by adding
golden-ratio offsets. Requires numpy. Output is deterministic for a given seed.
"""

from pathlib import Path

import numpy as np

SIZE = 128
SIGMA = 1.5
INITIAL_FRACTION = 0.1


def toroidal_kernel(size: int, sigma: float) -> np.ndarray:
    offsets = np.minimum(np.arange(size), size - np.arange(size)).astype(np.float64)
    squared = offsets[:, None] ** 2 + offsets[None, :] ** 2
    return np.exp(-squared / (2.0 * sigma * sigma))


class Energy:
    """Gaussian energy of a binary pattern on a torus, updated one pixel at a time."""

    def __init__(self, pattern: np.ndarray, kernel: np.ndarray):
        self.kernel = kernel
        spectrum = np.fft.fft2(pattern.astype(np.float64)) * np.fft.fft2(kernel)
        self.values = np.real(np.fft.ifft2(spectrum))

    def toggle(self, index: int, sign: float) -> None:
        row, column = divmod(index, SIZE)
        self.values += sign * np.roll(np.roll(self.kernel, row, axis=0), column, axis=1)


def rank_map(seed: int) -> np.ndarray:
    kernel = toroidal_kernel(SIZE, SIGMA)
    generator = np.random.default_rng(seed)
    total = SIZE * SIZE
    pattern = np.zeros(total, dtype=bool)
    ones = int(total * INITIAL_FRACTION)
    pattern[generator.choice(total, ones, replace=False)] = True

    # Relax the initial pattern: move the tightest cluster into the largest void until stable.
    energy = Energy(pattern.reshape(SIZE, SIZE), kernel)
    while True:
        flat = energy.values.ravel()
        cluster = int(np.argmax(np.where(pattern, flat, -np.inf)))
        pattern[cluster] = False
        energy.toggle(cluster, -1.0)
        flat = energy.values.ravel()
        void = int(np.argmin(np.where(pattern, np.inf, flat)))
        if void == cluster:
            pattern[cluster] = True
            energy.toggle(cluster, 1.0)
            break
        pattern[void] = True
        energy.toggle(void, 1.0)

    ranks = np.zeros(total, dtype=np.int64)
    prototype = pattern.copy()
    prototype_energy = energy.values.copy()

    # Phase 1: remove the tightest clusters, ranking the initial points from the top down.
    working = prototype.copy()
    for rank in range(ones - 1, -1, -1):
        flat = energy.values.ravel()
        cluster = int(np.argmax(np.where(working, flat, -np.inf)))
        working[cluster] = False
        energy.toggle(cluster, -1.0)
        ranks[cluster] = rank

    # Phases 2 and 3: fill the largest voids, ranking upward, until every pixel is placed.
    working = prototype.copy()
    energy.values = prototype_energy
    for rank in range(ones, total):
        flat = energy.values.ravel()
        void = int(np.argmin(np.where(working, np.inf, flat)))
        working[void] = True
        energy.toggle(void, 1.0)
        ranks[void] = rank
    return ranks.reshape(SIZE, SIZE)


def main() -> None:
    channels = [rank_map(seed) for seed in (1, 2)]
    quantised = [(channel * 256 // (SIZE * SIZE)).astype(np.uint8) for channel in channels]
    interleaved = np.stack(quantised, axis=-1).ravel()
    lines = [
        "// Generated by tools/generate_blue_noise.py; do not edit.",
        f"// {SIZE}x{SIZE} two-channel void-and-cluster blue noise, row-major RG8.",
    ]
    for start in range(0, interleaved.size, 24):
        lines.append(", ".join(str(int(value)) for value in interleaved[start:start + 24]) + ",")
    output = Path(__file__).resolve().parents[1] / "src/render/blue_noise_data.inc"
    output.write_text("\n".join(lines) + "\n")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
