#include "vulkan_lighting.hpp"

#include <FidelityFX/host/backends/vk/ffx_vk.h>
#include <FidelityFX/host/ffx_brixelizer.h>
#include <FidelityFX/host/ffx_brixelizergi.h>
#include <FidelityFX/host/ffx_classifier.h>
#include <FidelityFX/host/ffx_denoiser.h>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <limits>
#include <optional>
#include <unordered_map>

namespace relay {
namespace {

// 128x128 two-channel blue noise, generated by tools/generate_blue_noise.py.
constexpr std::uint8_t blue_noise_data[] = {
#include "../render/blue_noise_data.inc"
};
constexpr std::uint32_t blue_noise_size = 128U;
static_assert(sizeof(blue_noise_data) == blue_noise_size * blue_noise_size * 2U);
// Brixelizer GI reads one noise texture per frame; these are the blue noise shifted by the R2
// sequence, which keeps each frame's samples blue while decorrelating consecutive frames.
constexpr std::size_t noise_texture_count = 16U;

// Distance field layout. Cascade 0 has 0.1 m voxels over a 6.4 m cube around the camera; each
// further cascade doubles both, so the last of eight covers about 820 m.
constexpr std::uint32_t cascade_count = 8U;
constexpr float first_voxel_size = 0.1F;
constexpr float cascade_size_ratio = 2.0F;
// Relay's Brixelizer contexts use every cascade as static plus dynamic; the merged set that the
// GI traces through starts at twice the cascade count.
constexpr std::uint32_t merged_cascade_offset = 2U * cascade_count;
// Frames an object must stay still before it moves from the dynamic cascades, rebuilt every
// frame, back into the static ones, which only rebuild where something changed.
constexpr std::uint64_t settle_frames = 30U;
// Budgets for one distance field update.
constexpr std::uint32_t max_references = 1U << 23U;
constexpr std::uint32_t max_bricks_per_bake = 1U << 14U;
constexpr std::uint32_t triangle_swap_bytes = 64U << 20U;
constexpr std::uint32_t environment_size = 16U;

bool identical(const std::array<float, 16>& left, const std::array<float, 16>& right) {
    return std::memcmp(left.data(), right.data(), sizeof(left)) == 0;
}

struct Buffer {
    VkBuffer buffer{};
    VkDeviceMemory memory{};
    VkBufferCreateInfo info{};
};

struct Image {
    VkImage image{};
    VkDeviceMemory memory{};
    VkImageView view{};
    VkImageCreateInfo info{};
};

} // namespace

// Device helpers and the textures both lighting effects read: blue noise and the sky cube map.
struct LightingResources {
    LightingDevice gpu;
    VkPhysicalDeviceMemoryProperties memory_properties{};
    std::array<Image, noise_texture_count> noise{};
    Image environment;
    std::array<float, 3> environment_sky{-1.0F, -1.0F, -1.0F};
    std::array<float, 3> environment_ground{};

    bool initialize_resources(const LightingDevice& device, std::string& error) {
        gpu = device;
        vkGetPhysicalDeviceMemoryProperties(gpu.physical_device, &memory_properties);
        return create_noise(error);
    }

    void destroy_resources() {
        if (gpu.device == VK_NULL_HANDLE) return;
        for (auto& image : noise) destroy_image(image);
        destroy_image(environment);
    }

    std::optional<std::uint32_t> memory_type(const std::uint32_t allowed,
                                             const VkMemoryPropertyFlags required) const {
        for (std::uint32_t index = 0; index < memory_properties.memoryTypeCount; ++index)
            if ((allowed & (1U << index)) != 0U &&
                (memory_properties.memoryTypes[index].propertyFlags & required) == required)
                return index;
        return std::nullopt;
    }

    bool allocate(const VkMemoryRequirements& requirements, const VkMemoryPropertyFlags flags,
                  VkDeviceMemory& memory, std::string& error) {
        const auto type = memory_type(requirements.memoryTypeBits, flags);
        if (!type) {
            error = "no suitable memory type for a lighting resource";
            return false;
        }
        VkMemoryAllocateInfo allocation{};
        allocation.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        allocation.allocationSize = requirements.size;
        allocation.memoryTypeIndex = *type;
        if (vkAllocateMemory(gpu.device, &allocation, nullptr, &memory) != VK_SUCCESS) {
            error = "out of device memory for lighting resources";
            return false;
        }
        return true;
    }

    bool create_buffer(const VkDeviceSize size, const VkBufferUsageFlags usage, Buffer& buffer,
                       std::string& error,
                       const VkMemoryPropertyFlags flags = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT) {
        buffer.info = {};
        buffer.info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        buffer.info.size = size;
        buffer.info.usage = usage;
        buffer.info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(gpu.device, &buffer.info, nullptr, &buffer.buffer) != VK_SUCCESS) {
            error = "could not create a lighting buffer";
            return false;
        }
        VkMemoryRequirements requirements{};
        vkGetBufferMemoryRequirements(gpu.device, buffer.buffer, &requirements);
        if (!allocate(requirements, flags, buffer.memory, error)) return false;
        vkBindBufferMemory(gpu.device, buffer.buffer, buffer.memory, 0U);
        return true;
    }

    bool create_image(Image& image, const VkImageViewType view_type, std::string& error) {
        if (vkCreateImage(gpu.device, &image.info, nullptr, &image.image) != VK_SUCCESS) {
            error = "could not create a lighting image";
            return false;
        }
        VkMemoryRequirements requirements{};
        vkGetImageMemoryRequirements(gpu.device, image.image, &requirements);
        if (!allocate(requirements, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, image.memory, error))
            return false;
        vkBindImageMemory(gpu.device, image.image, image.memory, 0U);
        VkImageViewCreateInfo view{};
        view.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        view.image = image.image;
        view.viewType = view_type;
        view.format = image.info.format;
        view.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0U, image.info.mipLevels, 0U,
                                 image.info.arrayLayers};
        if (vkCreateImageView(gpu.device, &view, nullptr, &image.view) != VK_SUCCESS) {
            error = "could not create a lighting image view";
            return false;
        }
        return true;
    }

    static VkImageCreateInfo image_info(const VkImageType type, const VkFormat format,
                                        const VkExtent3D extent, const VkImageUsageFlags usage,
                                        const std::uint32_t layers = 1U) {
        VkImageCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
        info.imageType = type;
        info.format = format;
        info.extent = extent;
        info.mipLevels = 1U;
        info.arrayLayers = layers;
        info.samples = VK_SAMPLE_COUNT_1_BIT;
        info.tiling = VK_IMAGE_TILING_OPTIMAL;
        info.usage = usage;
        info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        info.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        return info;
    }

    void destroy_buffer(Buffer& buffer) {
        vkDestroyBuffer(gpu.device, buffer.buffer, nullptr);
        vkFreeMemory(gpu.device, buffer.memory, nullptr);
        buffer = {};
    }

    void destroy_image(Image& image) {
        vkDestroyImageView(gpu.device, image.view, nullptr);
        vkDestroyImage(gpu.device, image.image, nullptr);
        vkFreeMemory(gpu.device, image.memory, nullptr);
        image = {};
    }

    // Runs `record` in a one-time command buffer on the lighting queue and waits for it.
    template <typename Record> bool submit_once(Record&& record, std::string& error) {
        VkCommandPoolCreateInfo pool_info{};
        pool_info.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
        pool_info.flags = VK_COMMAND_POOL_CREATE_TRANSIENT_BIT;
        pool_info.queueFamilyIndex = gpu.queue_family;
        VkCommandPool pool{};
        if (vkCreateCommandPool(gpu.device, &pool_info, nullptr, &pool) != VK_SUCCESS) {
            error = "could not create a lighting upload command pool";
            return false;
        }
        VkCommandBufferAllocateInfo allocation{};
        allocation.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        allocation.commandPool = pool;
        allocation.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        allocation.commandBufferCount = 1U;
        VkCommandBuffer commands{};
        auto result = vkAllocateCommandBuffers(gpu.device, &allocation, &commands);
        VkCommandBufferBeginInfo begin{};
        begin.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        begin.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        if (result == VK_SUCCESS) result = vkBeginCommandBuffer(commands, &begin);
        if (result == VK_SUCCESS) {
            record(commands);
            result = vkEndCommandBuffer(commands);
        }
        VkSubmitInfo submit{};
        submit.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        submit.commandBufferCount = 1U;
        submit.pCommandBuffers = &commands;
        if (result == VK_SUCCESS) result = vkQueueSubmit(gpu.queue, 1U, &submit, VK_NULL_HANDLE);
        if (result == VK_SUCCESS) result = vkQueueWaitIdle(gpu.queue);
        vkDestroyCommandPool(gpu.device, pool, nullptr);
        if (result != VK_SUCCESS) {
            error = "lighting resource upload failed with Vulkan result " + std::to_string(result);
            return false;
        }
        return true;
    }

    static void transition(const VkCommandBuffer commands, const VkImage image,
                           const std::uint32_t layers, const VkImageLayout from,
                           const VkImageLayout to, const VkAccessFlags source_access,
                           const VkAccessFlags destination_access,
                           const VkPipelineStageFlags source_stage,
                           const VkPipelineStageFlags destination_stage) {
        VkImageMemoryBarrier barrier{};
        barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        barrier.srcAccessMask = source_access;
        barrier.dstAccessMask = destination_access;
        barrier.oldLayout = from;
        barrier.newLayout = to;
        barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.image = image;
        barrier.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0U, 1U, 0U, layers};
        vkCmdPipelineBarrier(commands, source_stage, destination_stage, 0U, 0U, nullptr, 0U,
                             nullptr, 1U, &barrier);
    }

    // Copies CPU pixel data into images, leaving them ready for shader reads.
    bool upload_images(const std::vector<std::pair<Image*, std::vector<std::byte>>>& uploads,
                       std::string& error) {
        VkDeviceSize total = 0U;
        for (const auto& upload : uploads) total += upload.second.size();
        Buffer staging;
        if (!create_buffer(total, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, staging, error,
                           VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                               VK_MEMORY_PROPERTY_HOST_COHERENT_BIT))
            return false;
        void* mapped = nullptr;
        if (vkMapMemory(gpu.device, staging.memory, 0U, total, 0U, &mapped) != VK_SUCCESS) {
            destroy_buffer(staging);
            error = "could not map the lighting staging buffer";
            return false;
        }
        VkDeviceSize offset = 0U;
        for (const auto& upload : uploads) {
            std::memcpy(static_cast<std::byte*>(mapped) + offset, upload.second.data(),
                        upload.second.size());
            offset += upload.second.size();
        }
        vkUnmapMemory(gpu.device, staging.memory);
        const bool uploaded = submit_once([&](const VkCommandBuffer commands) {
            VkDeviceSize source_offset = 0U;
            for (const auto& upload : uploads) {
                auto& image = *upload.first;
                const auto layers = image.info.arrayLayers;
                transition(commands, image.image, layers, VK_IMAGE_LAYOUT_UNDEFINED,
                           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0U, VK_ACCESS_TRANSFER_WRITE_BIT,
                           VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
                VkBufferImageCopy copy{};
                copy.bufferOffset = source_offset;
                copy.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0U, 0U, layers};
                copy.imageExtent = image.info.extent;
                vkCmdCopyBufferToImage(commands, staging.buffer, image.image,
                                       VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1U, &copy);
                transition(commands, image.image, layers, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                           VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_ACCESS_TRANSFER_WRITE_BIT,
                           VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                           VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
                source_offset += upload.second.size();
            }
        }, error);
        destroy_buffer(staging);
        return uploaded;
    }

    bool create_noise(std::string& error) {
        std::vector<std::pair<Image*, std::vector<std::byte>>> uploads;
        constexpr std::array<double, 2> r2{0.7548776662466927, 0.5698402909980532};
        for (std::size_t frame = 0; frame < noise_texture_count; ++frame) {
            auto& image = noise[frame];
            image.info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R8G8_UNORM,
                                    {blue_noise_size, blue_noise_size, 1U},
                                    VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT);
            if (!create_image(image, VK_IMAGE_VIEW_TYPE_2D, error)) return false;
            std::vector<std::byte> pixels(sizeof(blue_noise_data));
            for (std::size_t index = 0; index < pixels.size(); ++index) {
                const double shifted =
                    (blue_noise_data[index] + 0.5) / 256.0 + static_cast<double>(frame) * r2[index % 2U];
                pixels[index] = static_cast<std::byte>(
                    static_cast<std::uint8_t>((shifted - std::floor(shifted)) * 256.0));
            }
            uploads.emplace_back(&image, std::move(pixels));
        }
        return upload_images(uploads, error);
    }

    // The environment seen by rays that leave the distance field: Relay's analytic sky and
    // ground hemisphere, as a small cube map.
    bool update_environment(const std::array<float, 3>& sky, const std::array<float, 3>& ground,
                            std::string& error) {
        if (sky == environment_sky && ground == environment_ground && environment.image) return true;
        if (!environment.image) {
            environment.info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R32G32B32A32_SFLOAT,
                                          {environment_size, environment_size, 1U},
                                          VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
                                          6U);
            environment.info.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
            if (!create_image(environment, VK_IMAGE_VIEW_TYPE_CUBE, error)) return false;
        } else {
            vkQueueWaitIdle(gpu.queue);
        }
        std::vector<float> texels(6U * environment_size * environment_size * 4U);
        for (std::uint32_t face = 0; face < 6U; ++face)
            for (std::uint32_t y = 0; y < environment_size; ++y)
                for (std::uint32_t x = 0; x < environment_size; ++x) {
                    const float u = (static_cast<float>(x) + 0.5F) / environment_size * 2.0F - 1.0F;
                    const float v = (static_cast<float>(y) + 0.5F) / environment_size * 2.0F - 1.0F;
                    // Direction y per the Vulkan cube face order +X, -X, +Y, -Y, +Z, -Z.
                    const std::array<std::array<float, 3>, 6> directions{{
                        {1.0F, -v, -u}, {-1.0F, -v, u}, {u, 1.0F, v},
                        {u, -1.0F, -v}, {u, -v, 1.0F}, {-u, -v, -1.0F}}};
                    const auto& direction = directions[face];
                    const float length = std::sqrt(direction[0] * direction[0] +
                                                   direction[1] * direction[1] +
                                                   direction[2] * direction[2]);
                    const float t = std::clamp(direction[1] / length * 0.5F + 0.5F, 0.0F, 1.0F);
                    auto* texel = &texels[((face * environment_size + y) * environment_size + x) * 4U];
                    for (std::size_t channel = 0; channel < 3U; ++channel)
                        texel[channel] = ground[channel] + (sky[channel] - ground[channel]) * t;
                    texel[3] = 1.0F;
                }
        std::vector<std::byte> bytes(texels.size() * sizeof(float));
        std::memcpy(bytes.data(), texels.data(), bytes.size());
        if (!upload_images({{&environment, std::move(bytes)}}, error)) return false;
        environment_sky = sky;
        environment_ground = ground;
        return true;
    }

    static FfxResource buffer_resource(const Buffer& buffer, const wchar_t* name,
                                       const FfxResourceStates state) {
        auto description = ffxGetBufferResourceDescriptionVK(buffer.buffer, buffer.info,
                                                             FFX_RESOURCE_USAGE_UAV);
        description.stride = sizeof(std::uint32_t);
        return ffxGetResourceVK(reinterpret_cast<void*>(buffer.buffer), description, name, state);
    }

    static FfxResource image_resource(const VkImage image, const VkImageCreateInfo& info,
                                      const wchar_t* name, const FfxResourceStates state) {
        return ffxGetResourceVK(reinterpret_cast<void*>(image),
                                ffxGetImageResourceDescriptionVK(image, info), name, state);
    }

};

struct GlobalIllumination::Impl : LightingResources {
    std::vector<std::byte> backend_scratch;
    FfxInterface backend{};
    std::unique_ptr<FfxBrixelizerContext> brixelizer;
    std::unique_ptr<FfxBrixelizerGIContext> gi;
    std::unique_ptr<FfxBrixelizerBakedUpdateDescription> baked;
    bool brixelizer_ready{false};
    bool gi_ready{false};
    VkExtent2D gi_extent{};
    Image sdf_atlas;
    Buffer brick_aabbs;
    std::array<Buffer, FFX_BRIXELIZER_MAX_CASCADES> aabb_trees{};
    std::array<Buffer, FFX_BRIXELIZER_MAX_CASCADES> brick_maps{};
    Buffer update_scratch;
    Image diffuse, specular;
    // Registered mesh buffers by handle and size. A replaced buffer can reuse a destroyed one's
    // handle, but not while both sizes match and the old one is still registered, since the
    // renderer grows buffers rather than recreating them at the same size.
    struct RegisteredBuffer {
        std::uint32_t index{};
        std::uint64_t last_used{};
    };
    std::unordered_map<VkBuffer, std::unordered_map<VkDeviceSize, RegisteredBuffer>>
        registered_buffers;
    VkBuffer registered_index_buffer{};
    VkDeviceSize registered_index_bytes{};
    struct TrackedInstance {
        FfxBrixelizerInstanceID id{FFX_BRIXELIZER_INVALID_ID};
        LightingInstance source;
        std::uint64_t last_change{};
        std::uint64_t last_seen{};
    };
    std::unordered_map<std::uint64_t, TrackedInstance> tracked;
    LightingStatus current_status;

    ~Impl() { destroy(); }

    void release_outputs() {
        if (gi_ready) ffxBrixelizerGIContextDestroy(gi.get());
        gi_ready = false;
        gi_extent = {};
        destroy_image(diffuse);
        destroy_image(specular);
    }

    void destroy() {
        if (gpu.device == VK_NULL_HANDLE) return;
        release_outputs();
        if (brixelizer_ready) ffxBrixelizerContextDestroy(brixelizer.get());
        brixelizer_ready = false;
        destroy_image(sdf_atlas);
        destroy_buffer(brick_aabbs);
        for (auto& buffer : aabb_trees) destroy_buffer(buffer);
        for (auto& buffer : brick_maps) destroy_buffer(buffer);
        destroy_buffer(update_scratch);
        destroy_resources();
        tracked.clear();
        registered_buffers.clear();
        registered_index_buffer = VK_NULL_HANDLE;
        registered_index_bytes = 0U;
    }

    bool initialize(const LightingDevice& device, std::string& error) {
        if (!initialize_resources(device, error)) return false;
        constexpr std::size_t contexts = 2U;
        backend_scratch.resize(ffxGetScratchMemorySizeVK(gpu.physical_device, contexts));
        VkDeviceContext device_context{gpu.device, gpu.physical_device, vkGetDeviceProcAddr};
        if (ffxGetInterfaceVK(&backend, ffxGetDeviceVK(&device_context), backend_scratch.data(),
                              backend_scratch.size(), contexts) != FFX_OK) {
            error = "the FidelityFX Vulkan backend could not initialise";
            return false;
        }
        brixelizer = std::make_unique<FfxBrixelizerContext>();
        gi = std::make_unique<FfxBrixelizerGIContext>();
        baked = std::make_unique<FfxBrixelizerBakedUpdateDescription>();
        FfxBrixelizerContextDescription description{};
        description.numCascades = cascade_count;
        description.backendInterface = backend;
        float voxel_size = first_voxel_size;
        for (std::uint32_t cascade = 0; cascade < cascade_count; ++cascade) {
            description.cascadeDescs[cascade].flags = static_cast<FfxBrixelizerCascadeFlag>(
                FFX_BRIXELIZER_CASCADE_STATIC | FFX_BRIXELIZER_CASCADE_DYNAMIC);
            description.cascadeDescs[cascade].voxelSize = voxel_size;
            voxel_size *= cascade_size_ratio;
        }
        if (ffxBrixelizerContextCreate(&description, brixelizer.get()) != FFX_OK) {
            error = "the Brixelizer distance field context could not be created";
            return false;
        }
        brixelizer_ready = true;

        constexpr VkBufferUsageFlags storage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                               VK_BUFFER_USAGE_TRANSFER_DST_BIT |
                                               VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
        sdf_atlas.info = image_info(VK_IMAGE_TYPE_3D, VK_FORMAT_R8_UNORM,
                                    {FFX_BRIXELIZER_STATIC_CONFIG_SDF_ATLAS_SIZE,
                                     FFX_BRIXELIZER_STATIC_CONFIG_SDF_ATLAS_SIZE,
                                     FFX_BRIXELIZER_STATIC_CONFIG_SDF_ATLAS_SIZE},
                                    VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT |
                                        VK_IMAGE_USAGE_TRANSFER_DST_BIT);
        if (!create_image(sdf_atlas, VK_IMAGE_VIEW_TYPE_3D, error) ||
            !create_buffer(FFX_BRIXELIZER_BRICK_AABBS_SIZE, storage, brick_aabbs, error))
            return false;
        for (std::size_t cascade = 0; cascade < FFX_BRIXELIZER_MAX_CASCADES; ++cascade)
            if (!create_buffer(FFX_BRIXELIZER_CASCADE_AABB_TREE_SIZE, storage, aabb_trees[cascade],
                               error) ||
                !create_buffer(FFX_BRIXELIZER_CASCADE_BRICK_MAP_SIZE, storage, brick_maps[cascade],
                               error))
                return false;
        if (!create_buffer(64U << 20U, storage, update_scratch, error)) return false;
        // Brixelizer keeps these resources in the general layout; FidelityFX adds its barriers.
        if (!submit_once([&](const VkCommandBuffer commands) {
                transition(commands, sdf_atlas.image, 1U, VK_IMAGE_LAYOUT_UNDEFINED,
                           VK_IMAGE_LAYOUT_GENERAL, 0U,
                           VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT,
                           VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
            }, error))
            return false;
        current_status.available = true;
        return true;
    }

    bool ensure_outputs(const VkExtent2D extent, std::string& error) {
        if (gi_ready && extent.width == gi_extent.width && extent.height == gi_extent.height)
            return true;
        release_outputs();
        FfxBrixelizerGIContextDescription description{};
        description.flags = static_cast<FfxBrixelizerGIFlags>(0);
        // Native resolution: at 50% the downsample keeps each 2x2 block's closest depth, so the
        // low-resolution texels along a moving object's outline take its surface, and temporal
        // accumulation drags them into streaks along its path. Native costs about 0.15 ms more
        // at 1280x720 on an RX 9070 XT.
        description.internalResolution = FFX_BRIXELIZER_GI_INTERNAL_RESOLUTION_NATIVE;
        description.displaySize = {extent.width, extent.height};
        description.backendInterface = backend;
        if (ffxBrixelizerGIContextCreate(gi.get(), &description) != FFX_OK) {
            error = "the Brixelizer GI context could not be created";
            return false;
        }
        gi_ready = true;
        gi_extent = extent;
        for (auto* image : {&diffuse, &specular}) {
            image->info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R16G16B16A16_SFLOAT,
                                     {extent.width, extent.height, 1U},
                                     VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT);
            if (!create_image(*image, VK_IMAGE_VIEW_TYPE_2D, error)) return false;
        }
        return submit_once([&](const VkCommandBuffer commands) {
            for (auto* image : {&diffuse, &specular})
                transition(commands, image->image, 1U, VK_IMAGE_LAYOUT_UNDEFINED,
                           VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, 0U, VK_ACCESS_SHADER_READ_BIT,
                           VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                           VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
        }, error);
    }

    std::uint32_t buffer_index(const VkBuffer buffer, const VkDeviceSize size,
                               const std::uint64_t frame_index, std::string& error) {
        auto& sizes = registered_buffers[buffer];
        if (const auto found = sizes.find(size); found != sizes.end()) {
            found->second.last_used = frame_index;
            return found->second.index;
        }
        Buffer description;
        description.buffer = buffer;
        description.info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        description.info.size = size;
        description.info.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
        std::uint32_t index = 0U;
        FfxBrixelizerBufferDescription registration{};
        registration.buffer = buffer_resource(description, L"Relay mesh buffer",
                                              FFX_RESOURCE_STATE_COMPUTE_READ);
        registration.outIndex = &index;
        if (ffxBrixelizerRegisterBuffers(brixelizer.get(), &registration, 1U) != FFX_OK) {
            error = "Brixelizer refused a mesh buffer";
            return 0U;
        }
        sizes.emplace(size, RegisteredBuffer{index, frame_index});
        return index;
    }

    void unregister_buffers(const std::uint64_t unused_since) {
        std::vector<std::uint32_t> indices;
        for (auto buffer = registered_buffers.begin(); buffer != registered_buffers.end();) {
            for (auto size = buffer->second.begin(); size != buffer->second.end();) {
                if (size->second.last_used < unused_since) {
                    indices.push_back(size->second.index);
                    size = buffer->second.erase(size);
                } else {
                    ++size;
                }
            }
            buffer = buffer->second.empty() ? registered_buffers.erase(buffer) : std::next(buffer);
        }
        if (!indices.empty())
            ffxBrixelizerUnregisterBuffers(brixelizer.get(), indices.data(),
                                           static_cast<std::uint32_t>(indices.size()));
    }

    // Returns false only on a Brixelizer error. Objects are static unless they changed within the
    // last settle_frames frames or are deformed; changed static objects are deleted and
    // recreated, which invalidates the old and new areas of the static cascades.
    bool update_instances(const LightingFrame& frame, std::string& error) {
        if (frame.index_buffer != registered_index_buffer ||
            frame.index_buffer_bytes != registered_index_bytes) {
            // Asset uploads replaced the shared buffers; every instance refers to the old ones.
            std::vector<FfxBrixelizerInstanceID> stale;
            for (auto& [key, instance] : tracked)
                if (instance.id != FFX_BRIXELIZER_INVALID_ID) stale.push_back(instance.id);
            if (!stale.empty() && ffxBrixelizerDeleteInstances(brixelizer.get(), stale.data(),
                                                               static_cast<std::uint32_t>(stale.size())) != FFX_OK) {
                error = "Brixelizer could not delete instances";
                return false;
            }
            tracked.clear();
            unregister_buffers(std::numeric_limits<std::uint64_t>::max());
            registered_index_buffer = frame.index_buffer;
            registered_index_bytes = frame.index_buffer_bytes;
        }
        const auto index_buffer =
            buffer_index(frame.index_buffer, frame.index_buffer_bytes, frame.frame_index, error);
        if (!error.empty()) return false;

        std::vector<FfxBrixelizerInstanceID> deleted;
        std::vector<FfxBrixelizerInstanceDescription> created;
        std::vector<std::uint64_t> created_keys;
        std::vector<FfxBrixelizerInstanceID> created_ids;
        current_status.static_instances = 0U;
        current_status.dynamic_instances = 0U;
        const auto describe = [&](const LightingInstance& instance, const bool dynamic) {
            FfxBrixelizerInstanceDescription description{};
            description.maxCascade = cascade_count - 1U;
            for (std::size_t axis = 0; axis < 3U; ++axis) {
                description.aabb.min[axis] = instance.bounds_min[axis];
                description.aabb.max[axis] = instance.bounds_max[axis];
            }
            // Brixelizer takes the top three rows of the world transform, row by row.
            for (std::size_t row = 0; row < 3U; ++row)
                for (std::size_t column = 0; column < 4U; ++column)
                    description.transform[row * 4U + column] = instance.model[column * 4U + row];
            description.indexFormat = FFX_INDEX_TYPE_UINT32;
            description.indexBuffer = index_buffer;
            description.indexBufferOffset = instance.first_index * sizeof(std::uint32_t);
            description.triangleCount = instance.index_count / 3U;
            description.vertexBuffer = buffer_index(instance.vertex_buffer,
                                                    instance.vertex_buffer_bytes, frame.frame_index,
                                                    error);
            description.vertexStride = instance.vertex_stride;
            description.vertexBufferOffset = instance.first_vertex * instance.vertex_stride;
            description.vertexCount = instance.vertex_count;
            description.vertexFormat = FFX_SURFACE_FORMAT_R32G32B32_FLOAT;
            description.flags = dynamic ? FFX_BRIXELIZER_INSTANCE_FLAG_DYNAMIC
                                        : FFX_BRIXELIZER_INSTANCE_FLAG_NONE;
            return description;
        };
        for (const auto& instance : frame.instances) {
            if (instance.index_count < 3U) continue;
            auto [entry, inserted] = tracked.try_emplace(instance.key);
            auto& state = entry->second;
            const bool changed =
                inserted || state.source.vertex_buffer != instance.vertex_buffer ||
                state.source.first_index != instance.first_index ||
                state.source.index_count != instance.index_count ||
                state.source.first_vertex != instance.first_vertex ||
                !identical(state.source.model, instance.model);
            if (changed) state.last_change = frame.frame_index;
            state.last_seen = frame.frame_index;
            const bool dynamic = instance.deformed ||
                                 frame.frame_index - state.last_change < settle_frames;
            if (state.id != FFX_BRIXELIZER_INVALID_ID && (changed || dynamic)) {
                deleted.push_back(state.id);
                state.id = FFX_BRIXELIZER_INVALID_ID;
            }
            state.source = instance;
            if (dynamic) {
                // Dynamic instances live for one update and are rebuilt every frame.
                created.push_back(describe(instance, true));
                created_keys.push_back(0U);
                ++current_status.dynamic_instances;
            } else if (state.id == FFX_BRIXELIZER_INVALID_ID) {
                created.push_back(describe(instance, false));
                created_keys.push_back(instance.key);
                ++current_status.static_instances;
            } else {
                ++current_status.static_instances;
            }
            if (!error.empty()) return false;
        }
        for (auto entry = tracked.begin(); entry != tracked.end();) {
            if (entry->second.last_seen != frame.frame_index) {
                if (entry->second.id != FFX_BRIXELIZER_INVALID_ID) deleted.push_back(entry->second.id);
                entry = tracked.erase(entry);
            } else {
                ++entry;
            }
        }
        if (!deleted.empty() &&
            ffxBrixelizerDeleteInstances(brixelizer.get(), deleted.data(),
                                         static_cast<std::uint32_t>(deleted.size())) != FFX_OK) {
            error = "Brixelizer could not delete instances";
            return false;
        }
        created_ids.assign(created.size(), FFX_BRIXELIZER_INVALID_ID);
        for (std::size_t index = 0; index < created.size(); ++index)
            if (created_keys[index] != 0U) created[index].outInstanceID = &created_ids[index];
        if (!created.empty() &&
            ffxBrixelizerCreateInstances(brixelizer.get(), created.data(),
                                         static_cast<std::uint32_t>(created.size())) != FFX_OK) {
            error = "Brixelizer could not create instances";
            return false;
        }
        for (std::size_t index = 0; index < created.size(); ++index)
            if (created_keys[index] != 0U) tracked[created_keys[index]].id = created_ids[index];
        // Keep buffers that frames in flight or this frame's instances still use.
        if (frame.frame_index > 4U) unregister_buffers(frame.frame_index - 4U);
        return true;
    }

    FfxBrixelizerResources scene_resources(const FfxResourceStates state) const {
        FfxBrixelizerResources resources{};
        resources.sdfAtlas = image_resource(sdf_atlas.image, sdf_atlas.info, L"Brixelizer SDF atlas",
                                            state);
        resources.brickAABBs = buffer_resource(brick_aabbs, L"Brixelizer brick AABBs", state);
        for (std::size_t cascade = 0; cascade < FFX_BRIXELIZER_MAX_CASCADES; ++cascade) {
            resources.cascadeResources[cascade].aabbTree =
                buffer_resource(aabb_trees[cascade], L"Brixelizer cascade AABB tree", state);
            resources.cascadeResources[cascade].brickMap =
                buffer_resource(brick_maps[cascade], L"Brixelizer cascade brick map", state);
        }
        return resources;
    }

    bool record(const LightingFrame& frame, std::string& error) {
        if (!brixelizer_ready) {
            error = "global illumination is not initialised";
            return false;
        }
        if (!update_environment(frame.sky_color, frame.ground_color, error) ||
            !ensure_outputs(frame.extent, error) || !update_instances(frame, error))
            return false;

        FfxBrixelizerStats stats{};
        FfxBrixelizerUpdateDescription update{};
        update.resources = scene_resources(FFX_RESOURCE_STATE_UNORDERED_ACCESS);
        update.frameIndex = static_cast<std::uint32_t>(frame.frame_index);
        std::copy(frame.camera_position.begin(), frame.camera_position.end(), update.sdfCenter);
        update.populateDebugAABBsFlags = FFX_BRIXELIZER_POPULATE_AABBS_NONE;
        update.maxReferences = max_references;
        update.triangleSwapSize = triangle_swap_bytes;
        update.maxBricksPerBake = max_bricks_per_bake;
        std::size_t scratch_bytes = 0U;
        update.outScratchBufferSize = &scratch_bytes;
        update.outStats = &stats;
        if (ffxBrixelizerBakeUpdate(brixelizer.get(), &update, baked.get()) != FFX_OK) {
            error = "Brixelizer could not prepare its update";
            return false;
        }
        if (scratch_bytes > update_scratch.info.size) {
            // Rare: the scene outgrew the scratch buffer. Frames in flight may still use it.
            vkDeviceWaitIdle(gpu.device);
            destroy_buffer(update_scratch);
            if (!create_buffer(std::max<VkDeviceSize>(scratch_bytes, update_scratch.info.size * 2U),
                               VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT |
                                   VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                               update_scratch, error))
                return false;
        }
        current_status.scratch_bytes = update_scratch.info.size;
        const auto commands = ffxGetCommandListVK(frame.commands);
        if (ffxBrixelizerUpdate(brixelizer.get(), baked.get(),
                                buffer_resource(update_scratch, L"Brixelizer scratch",
                                                FFX_RESOURCE_STATE_UNORDERED_ACCESS),
                                commands) != FFX_OK) {
            error = "Brixelizer could not record its update";
            return false;
        }

        FfxBrixelizerGIDispatchDescription dispatch{};
        // FidelityFX expects Direct3D clip space, where y points up; Relay's projection points it
        // down for Vulkan's framebuffer. Depth and the UV layout of every image already agree.
        auto projection = frame.projection;
        auto previous_projection = frame.previous_projection;
        projection[5] = -projection[5];
        previous_projection[5] = -previous_projection[5];
        std::memcpy(&dispatch.view, frame.view.data(), sizeof(dispatch.view));
        std::memcpy(&dispatch.projection, projection.data(), sizeof(dispatch.projection));
        std::memcpy(&dispatch.prevView, frame.previous_view.data(), sizeof(dispatch.prevView));
        std::memcpy(&dispatch.prevProjection, previous_projection.data(),
                    sizeof(dispatch.prevProjection));
        std::copy(frame.camera_position.begin(), frame.camera_position.end(), dispatch.cameraPosition);
        dispatch.startCascade = merged_cascade_offset;
        dispatch.endCascade = merged_cascade_offset + cascade_count - 1U;
        dispatch.rayPushoff = 0.25F;
        dispatch.sdfSolveEps = 0.5F;
        dispatch.specularRayPushoff = 0.25F;
        dispatch.specularSDFSolveEps = 0.5F;
        dispatch.tMin = 0.0F;
        dispatch.tMax = 10000.0F;
        constexpr auto read = FFX_RESOURCE_STATE_PIXEL_COMPUTE_READ;
        dispatch.environmentMap = image_resource(environment.image, environment.info,
                                                 L"Relay sky", read);
        dispatch.prevLitOutput = image_resource(frame.previous_lit.image, frame.previous_lit.info,
                                                L"Relay previous lit output", read);
        dispatch.depth = image_resource(frame.depth.image, frame.depth.info, L"Relay depth", read);
        dispatch.historyDepth = image_resource(frame.history_depth.image, frame.history_depth.info,
                                               L"Relay history depth", read);
        dispatch.normal = image_resource(frame.normal_roughness.image, frame.normal_roughness.info,
                                         L"Relay normals", read);
        dispatch.historyNormal = image_resource(frame.history_normal_roughness.image,
                                                frame.history_normal_roughness.info,
                                                L"Relay history normals", read);
        dispatch.roughness = dispatch.normal;
        dispatch.motionVectors = image_resource(frame.motion.image, frame.motion.info,
                                                L"Relay motion vectors", read);
        const auto& noise_image = noise[frame.frame_index % noise_texture_count];
        dispatch.noiseTexture = image_resource(noise_image.image, noise_image.info,
                                               L"Relay blue noise", read);
        dispatch.normalsUnpackMul = 1.0F;
        dispatch.normalsUnpackAdd = 0.0F;
        dispatch.isRoughnessPerceptual = true;
        dispatch.roughnessChannel = 3U;
        dispatch.roughnessThreshold = 0.9F;
        // Relay's sky and ground colors are tuned as the analytic ambient term, which divides
        // them by pi; the same scale keeps overall brightness when GI takes over.
        dispatch.environmentMapIntensity = 1.0F / 3.14159265F;
        dispatch.motionVectorScale = {1.0F, 1.0F};
        const auto resources = scene_resources(FFX_RESOURCE_STATE_UNORDERED_ACCESS);
        dispatch.sdfAtlas = resources.sdfAtlas;
        dispatch.bricksAABBs = resources.brickAABBs;
        for (std::size_t cascade = 0; cascade < FFX_BRIXELIZER_MAX_CASCADES; ++cascade) {
            dispatch.cascadeAABBTrees[cascade] = resources.cascadeResources[cascade].aabbTree;
            dispatch.cascadeBrickMaps[cascade] = resources.cascadeResources[cascade].brickMap;
        }
        dispatch.outputDiffuseGI = image_resource(diffuse.image, diffuse.info, L"Relay diffuse GI", read);
        dispatch.outputSpecularGI = image_resource(specular.image, specular.info,
                                                   L"Relay specular GI", read);
        if (ffxBrixelizerGetRawContext(brixelizer.get(), &dispatch.brixelizerContext) != FFX_OK ||
            ffxBrixelizerGIContextDispatch(gi.get(), &dispatch, commands) != FFX_OK) {
            error = "Brixelizer GI could not record its dispatch";
            return false;
        }
        return true;
    }
};

GlobalIllumination::GlobalIllumination() : impl_(std::make_unique<Impl>()) {}
GlobalIllumination::~GlobalIllumination() = default;

bool GlobalIllumination::initialize(const LightingDevice& device, std::string& error) {
    if (impl_->initialize(device, error)) return true;
    impl_->current_status.error = error;
    impl_->destroy();
    return false;
}

bool GlobalIllumination::record(const LightingFrame& frame, std::string& error) {
    const bool recorded = impl_->record(frame, error);
    impl_->current_status.error = recorded ? std::string{} : error;
    return recorded;
}

void GlobalIllumination::release_outputs() { impl_->release_outputs(); }
VkImageView GlobalIllumination::diffuse_view() const { return impl_->diffuse.view; }
VkImageView GlobalIllumination::specular_view() const { return impl_->specular.view; }
VkExtent2D GlobalIllumination::extent() const { return impl_->gi_extent; }
LightingStatus GlobalIllumination::status() const { return impl_->current_status; }

} // namespace relay

namespace relay {
namespace {

using Matrix = std::array<float, 16>;

// Column-major product and inverse, for the matrices FidelityFX derives from the camera.
Matrix multiply(const Matrix& left, const Matrix& right) {
    Matrix product{};
    for (std::size_t row = 0; row < 4U; ++row)
        for (std::size_t column = 0; column < 4U; ++column)
            for (std::size_t inner = 0; inner < 4U; ++inner)
                product[column * 4U + row] += left[inner * 4U + row] * right[column * 4U + inner];
    return product;
}

Matrix invert(const Matrix& m) {
    // Gauss-Jordan elimination with partial pivoting on a column-major matrix.
    std::array<std::array<double, 8>, 4> rows{};
    for (std::size_t row = 0; row < 4U; ++row) {
        for (std::size_t column = 0; column < 4U; ++column) rows[row][column] = m[column * 4U + row];
        rows[row][4U + row] = 1.0;
    }
    for (std::size_t column = 0; column < 4U; ++column) {
        std::size_t pivot = column;
        for (std::size_t row = column + 1U; row < 4U; ++row)
            if (std::abs(rows[row][column]) > std::abs(rows[pivot][column])) pivot = row;
        if (std::abs(rows[pivot][column]) < 1e-30) return {};
        std::swap(rows[column], rows[pivot]);
        const double scale = 1.0 / rows[column][column];
        for (auto& value : rows[column]) value *= scale;
        for (std::size_t row = 0; row < 4U; ++row) {
            if (row == column) continue;
            const double factor = rows[row][column];
            for (std::size_t index = 0; index < 8U; ++index)
                rows[row][index] -= factor * rows[column][index];
        }
    }
    Matrix inverse{};
    for (std::size_t row = 0; row < 4U; ++row)
        for (std::size_t column = 0; column < 4U; ++column)
            inverse[column * 4U + row] = static_cast<float>(rows[row][4U + column]);
    return inverse;
}

// FidelityFX expects Direct3D clip space, where y points up.
Matrix direct3d_projection(Matrix projection) {
    projection[5] = -projection[5];
    return projection;
}

// Classifier mask bits, from ffx_classifier_reflections_common.h: trace every ray with hardware
// ray tracing and none in screen space.
constexpr std::uint32_t classifier_use_ray_tracing = 1U << 2U;

} // namespace

struct Reflections::Impl : LightingResources {
    std::vector<std::byte> backend_scratch;
    FfxInterface backend{};
    std::unique_ptr<FfxClassifierContext> classifier;
    std::unique_ptr<FfxDenoiserContext> denoiser;
    bool contexts_ready{false};
    VkExtent2D extent{};
    std::array<Image, 2> radiance{}, variance{}, hit_counter{};
    Image extracted_roughness, output;
    Buffer ray_list, hardware_ray_list, denoiser_tiles, ray_counter, arguments;
    LightingStatus current_status;

    ~Impl() { destroy(); }

    void release_targets() {
        if (contexts_ready) {
            ffxClassifierContextDestroy(classifier.get());
            ffxDenoiserContextDestroy(denoiser.get());
        }
        contexts_ready = false;
        extent = {};
        for (auto& image : radiance) destroy_image(image);
        for (auto& image : variance) destroy_image(image);
        for (auto& image : hit_counter) destroy_image(image);
        destroy_image(extracted_roughness);
        destroy_image(output);
        for (auto* buffer : {&ray_list, &hardware_ray_list, &denoiser_tiles, &ray_counter, &arguments})
            destroy_buffer(*buffer);
    }

    void destroy() {
        if (gpu.device == VK_NULL_HANDLE) return;
        release_targets();
        destroy_resources();
    }

    bool initialize(const LightingDevice& device, std::string& error) {
        if (!initialize_resources(device, error)) return false;
        constexpr std::size_t contexts = 2U;
        backend_scratch.resize(ffxGetScratchMemorySizeVK(gpu.physical_device, contexts));
        VkDeviceContext device_context{gpu.device, gpu.physical_device, vkGetDeviceProcAddr};
        if (ffxGetInterfaceVK(&backend, ffxGetDeviceVK(&device_context), backend_scratch.data(),
                              backend_scratch.size(), contexts) != FFX_OK) {
            error = "the FidelityFX Vulkan backend could not initialise";
            return false;
        }
        classifier = std::make_unique<FfxClassifierContext>();
        denoiser = std::make_unique<FfxDenoiserContext>();
        current_status.available = true;
        return true;
    }

    bool ensure_targets(const VkExtent2D size, std::string& error) {
        if (contexts_ready && size.width == extent.width && size.height == extent.height) return true;
        release_targets();
        FfxClassifierContextDescription classifier_description{};
        classifier_description.flags = FFX_CLASSIFIER_REFLECTION;
        classifier_description.resolution = {size.width, size.height};
        classifier_description.backendInterface = backend;
        FfxDenoiserContextDescription denoiser_description{};
        denoiser_description.flags = FFX_DENOISER_REFLECTIONS;
        denoiser_description.windowSize = {size.width, size.height};
        denoiser_description.normalsHistoryBufferFormat = FFX_SURFACE_FORMAT_R16G16B16A16_FLOAT;
        denoiser_description.backendInterface = backend;
        if (ffxClassifierContextCreate(classifier.get(), &classifier_description) != FFX_OK) {
            error = "the FidelityFX reflection classifier could not be created";
            return false;
        }
        if (ffxDenoiserContextCreate(denoiser.get(), &denoiser_description) != FFX_OK) {
            ffxClassifierContextDestroy(classifier.get());
            error = "the FidelityFX reflection denoiser could not be created";
            return false;
        }
        contexts_ready = true;
        extent = size;
        const VkExtent3D full{size.width, size.height, 1U};
        const VkExtent3D tiles{(size.width + 7U) / 8U, (size.height + 7U) / 8U, 1U};
        // Cleared on creation, and copied by the denoiser into its history.
        constexpr VkImageUsageFlags storage = VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT |
                                              VK_IMAGE_USAGE_TRANSFER_SRC_BIT |
                                              VK_IMAGE_USAGE_TRANSFER_DST_BIT;
        for (std::size_t index = 0; index < 2U; ++index) {
            radiance[index].info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R16G16B16A16_SFLOAT, full, storage);
            variance[index].info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R16_SFLOAT, full, storage);
            hit_counter[index].info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R32_UINT, tiles, storage);
            if (!create_image(radiance[index], VK_IMAGE_VIEW_TYPE_2D, error) ||
                !create_image(variance[index], VK_IMAGE_VIEW_TYPE_2D, error) ||
                !create_image(hit_counter[index], VK_IMAGE_VIEW_TYPE_2D, error))
                return false;
        }
        // R8, like the denoiser's roughness history it is copied into.
        extracted_roughness.info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R8_UNORM, full, storage);
        output.info = image_info(VK_IMAGE_TYPE_2D, VK_FORMAT_R16G16B16A16_SFLOAT, full, storage);
        if (!create_image(extracted_roughness, VK_IMAGE_VIEW_TYPE_2D, error) ||
            !create_image(output, VK_IMAGE_VIEW_TYPE_2D, error))
            return false;
        const VkDeviceSize pixels = static_cast<VkDeviceSize>(size.width) * size.height;
        constexpr VkBufferUsageFlags buffer_usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                                    VK_BUFFER_USAGE_TRANSFER_DST_BIT;
        if (!create_buffer(pixels * sizeof(std::uint32_t), buffer_usage, ray_list, error) ||
            !create_buffer(pixels * sizeof(std::uint32_t), buffer_usage, hardware_ray_list, error) ||
            !create_buffer(static_cast<VkDeviceSize>(tiles.width) * tiles.height * sizeof(std::uint32_t),
                           buffer_usage, denoiser_tiles, error) ||
            !create_buffer(8U * sizeof(std::uint32_t), buffer_usage, ray_counter, error) ||
            !create_buffer(12U * sizeof(std::uint32_t),
                           buffer_usage | VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT, arguments, error))
            return false;
        // Start from empty counters, cleared history and every image in its steady layout.
        return submit_once([&](const VkCommandBuffer commands) {
            vkCmdFillBuffer(commands, ray_counter.buffer, 0U, VK_WHOLE_SIZE, 0U);
            vkCmdFillBuffer(commands, arguments.buffer, 0U, VK_WHOLE_SIZE, 0U);
            std::vector<Image*> general{&radiance[0], &radiance[1], &variance[0], &variance[1],
                                        &hit_counter[0], &hit_counter[1], &extracted_roughness};
            for (auto* image : general) {
                transition(commands, image->image, 1U, VK_IMAGE_LAYOUT_UNDEFINED,
                           VK_IMAGE_LAYOUT_GENERAL, 0U, VK_ACCESS_TRANSFER_WRITE_BIT,
                           VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
                const VkClearColorValue zero{};
                const VkImageSubresourceRange range{VK_IMAGE_ASPECT_COLOR_BIT, 0U, 1U, 0U, 1U};
                vkCmdClearColorImage(commands, image->image, VK_IMAGE_LAYOUT_GENERAL, &zero, 1U, &range);
            }
            transition(commands, output.image, 1U, VK_IMAGE_LAYOUT_UNDEFINED,
                       VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, 0U, VK_ACCESS_SHADER_READ_BIT,
                       VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
            VkMemoryBarrier barrier{};
            barrier.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
            barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
            vkCmdPipelineBarrier(commands, VK_PIPELINE_STAGE_TRANSFER_BIT,
                                 VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0U, 1U, &barrier, 0U,
                                 nullptr, 0U, nullptr);
        }, error);
    }

    // The ping-pong images: A receives this frame's rays, B holds the previous frame.
    std::size_t current(const std::uint64_t frame_index) const { return (frame_index & 1U) ? 0U : 1U; }

    bool record_classification(const ReflectionFrame& frame, std::string& error) {
        if (!update_environment(frame.sky_color, frame.ground_color, error) ||
            !ensure_targets(frame.extent, error))
            return false;
        const auto a = current(frame.frame_index);
        const auto b = 1U - a;
        const auto projection = direct3d_projection(frame.projection);
        const auto view_projection = multiply(projection, frame.view);
        const auto previous_view_projection =
            multiply(direct3d_projection(frame.previous_projection), frame.previous_view);
        const auto inverse_view_projection = invert(view_projection);
        const auto inverse_projection = invert(projection);
        const auto inverse_view = invert(frame.view);
        constexpr auto read = FFX_RESOURCE_STATE_PIXEL_COMPUTE_READ;
        constexpr auto write = FFX_RESOURCE_STATE_UNORDERED_ACCESS;
        FfxClassifierReflectionDispatchDescription dispatch{};
        dispatch.commandList = ffxGetCommandListVK(frame.commands);
        dispatch.depth = image_resource(frame.depth.image, frame.depth.info, L"Relay depth", read);
        dispatch.motionVectors = image_resource(frame.motion.image, frame.motion.info,
                                                L"Relay motion vectors", read);
        dispatch.normal = image_resource(frame.normal_roughness.image, frame.normal_roughness.info,
                                         L"Relay normals", read);
        dispatch.materialParameters = dispatch.normal;
        dispatch.environmentMap = image_resource(environment.image, environment.info, L"Relay sky", read);
        dispatch.radiance = image_resource(radiance[a].image, radiance[a].info, L"Reflection radiance", write);
        dispatch.varianceHistory = image_resource(variance[b].image, variance[b].info,
                                                  L"Reflection variance history", write);
        dispatch.hitCounter = image_resource(hit_counter[a].image, hit_counter[a].info,
                                             L"Reflection hit counter", write);
        dispatch.hitCounterHistory = image_resource(hit_counter[b].image, hit_counter[b].info,
                                                    L"Reflection hit counter history", write);
        dispatch.rayList = buffer_resource(ray_list, L"Reflection ray list", write);
        dispatch.rayListHW = buffer_resource(hardware_ray_list, L"Reflection hardware ray list", write);
        dispatch.extractedRoughness = image_resource(extracted_roughness.image, extracted_roughness.info,
                                                     L"Reflection roughness", write);
        dispatch.rayCounter = buffer_resource(ray_counter, L"Reflection ray counter", write);
        dispatch.denoiserTileList = buffer_resource(denoiser_tiles, L"Reflection denoiser tiles", write);
        dispatch.renderSize = {frame.extent.width, frame.extent.height};
        std::memcpy(dispatch.invViewProjection, inverse_view_projection.data(), sizeof(dispatch.invViewProjection));
        std::memcpy(dispatch.projection, projection.data(), sizeof(dispatch.projection));
        std::memcpy(dispatch.invProjection, inverse_projection.data(), sizeof(dispatch.invProjection));
        std::memcpy(dispatch.view, frame.view.data(), sizeof(dispatch.view));
        std::memcpy(dispatch.invView, inverse_view.data(), sizeof(dispatch.invView));
        std::memcpy(dispatch.prevViewProjection, previous_view_projection.data(),
                    sizeof(dispatch.prevViewProjection));
        // Relay's sky and ground are tuned as the analytic ambient term, which divides by pi.
        dispatch.iblFactor = 1.0F / 3.14159265F;
        dispatch.frameIndex = static_cast<std::uint32_t>(frame.frame_index);
        dispatch.samplesPerQuad = 4U;
        dispatch.temporalVarianceGuidedTracingEnabled = 0U;
        dispatch.globalRoughnessThreshold = reflection_roughness_threshold;
        dispatch.rtRoughnessThreshold = reflection_roughness_threshold;
        dispatch.mask = classifier_use_ray_tracing;
        dispatch.reflectionWidth = frame.extent.width;
        dispatch.reflectionHeight = frame.extent.height;
        dispatch.hybridMissWeight = 0.5F;
        dispatch.hybridSpawnRate = 0.02F;
        dispatch.vrtVarianceThreshold = 0.02F;
        dispatch.reflectionsBackfacingThreshold = 1.0F;
        dispatch.randomSamplesPerPixel = 32U;
        // The classifier reads motion as current minus previous; Relay stores the reverse.
        dispatch.motionVectorScale[0] = -1.0F;
        dispatch.motionVectorScale[1] = -1.0F;
        dispatch.normalsUnpackMul = 1.0F;
        dispatch.normalsUnpackAdd = 0.0F;
        dispatch.roughnessChannel = 3U;
        dispatch.isRoughnessPerceptual = true;
        if (ffxClassifierContextReflectionDispatch(classifier.get(), &dispatch) != FFX_OK) {
            error = "the reflection classifier could not record its dispatch";
            return false;
        }
        return true;
    }

    bool record_denoising(const ReflectionFrame& frame, std::string& error) {
        const auto a = current(frame.frame_index);
        const auto b = 1U - a;
        const auto projection = direct3d_projection(frame.projection);
        const auto previous_view_projection =
            multiply(direct3d_projection(frame.previous_projection), frame.previous_view);
        const auto inverse_projection = invert(projection);
        const auto inverse_view = invert(frame.view);
        constexpr auto read = FFX_RESOURCE_STATE_PIXEL_COMPUTE_READ;
        constexpr auto write = FFX_RESOURCE_STATE_UNORDERED_ACCESS;
        FfxDenoiserReflectionsDispatchDescription dispatch{};
        dispatch.commandList = ffxGetCommandListVK(frame.commands);
        // The denoiser only reads the most detailed level of the depth hierarchy.
        dispatch.depthHierarchy = image_resource(frame.depth.image, frame.depth.info, L"Relay depth", read);
        dispatch.motionVectors = image_resource(frame.motion.image, frame.motion.info,
                                                L"Relay motion vectors", read);
        dispatch.normal = image_resource(frame.normal_roughness.image, frame.normal_roughness.info,
                                         L"Relay normals", read);
        dispatch.radianceA = image_resource(radiance[a].image, radiance[a].info, L"Reflection radiance A", write);
        dispatch.radianceB = image_resource(radiance[b].image, radiance[b].info, L"Reflection radiance B", write);
        dispatch.varianceA = image_resource(variance[a].image, variance[a].info, L"Reflection variance A", write);
        dispatch.varianceB = image_resource(variance[b].image, variance[b].info, L"Reflection variance B", write);
        dispatch.extractedRoughness = image_resource(extracted_roughness.image, extracted_roughness.info,
                                                     L"Reflection roughness", write);
        dispatch.denoiserTileList = buffer_resource(denoiser_tiles, L"Reflection denoiser tiles", write);
        dispatch.indirectArgumentsBuffer = buffer_resource(arguments, L"Reflection indirect arguments",
                                                           FFX_RESOURCE_STATE_INDIRECT_ARGUMENT);
        dispatch.output = image_resource(output.image, output.info, L"Reflections", read);
        dispatch.renderSize = {frame.extent.width, frame.extent.height};
        dispatch.motionVectorScale = {1.0F, 1.0F};
        std::memcpy(dispatch.invProjection, inverse_projection.data(), sizeof(dispatch.invProjection));
        std::memcpy(dispatch.invView, inverse_view.data(), sizeof(dispatch.invView));
        std::memcpy(dispatch.prevViewProjection, previous_view_projection.data(),
                    sizeof(dispatch.prevViewProjection));
        dispatch.normalsUnpackMul = 1.0F;
        dispatch.normalsUnpackAdd = 0.0F;
        dispatch.isRoughnessPerceptual = true;
        dispatch.roughnessChannel = 3U;
        dispatch.temporalStabilityFactor = 0.7F;
        dispatch.roughnessThreshold = reflection_roughness_threshold;
        dispatch.frameIndex = static_cast<std::uint32_t>(frame.frame_index);
        dispatch.reset = frame.reset;
        if (ffxDenoiserContextDispatchReflections(denoiser.get(), &dispatch) != FFX_OK) {
            error = "the reflection denoiser could not record its dispatch";
            return false;
        }
        return true;
    }
};

Reflections::Reflections() : impl_(std::make_unique<Impl>()) {}
Reflections::~Reflections() = default;

bool Reflections::initialize(const LightingDevice& device, std::string& error) {
    if (impl_->initialize(device, error)) return true;
    impl_->current_status.error = error;
    impl_->destroy();
    return false;
}

bool Reflections::record_classification(const ReflectionFrame& frame, std::string& error) {
    const bool recorded = impl_->record_classification(frame, error);
    impl_->current_status.error = recorded ? std::string{} : error;
    return recorded;
}

bool Reflections::record_denoising(const ReflectionFrame& frame, std::string& error) {
    const bool recorded = impl_->record_denoising(frame, error);
    impl_->current_status.error = recorded ? std::string{} : error;
    return recorded;
}

ReflectionTargets Reflections::targets(const std::uint64_t frame_index) const {
    const auto a = impl_->current(frame_index);
    return {impl_->hardware_ray_list.buffer, impl_->ray_counter.buffer, impl_->arguments.buffer,
            impl_->radiance[a].view, impl_->variance[a].view};
}

VkImageView Reflections::output() const { return impl_->output.view; }
VkImageView Reflections::noise(const std::uint64_t frame_index) const {
    return impl_->noise[frame_index % noise_texture_count].view;
}
VkExtent2D Reflections::extent() const { return impl_->extent; }
LightingStatus Reflections::status() const { return impl_->current_status; }

} // namespace relay
